### ISSUE TITLE
Best way to vizualise segmentation in 3D?

### ISSUE THREAD

**Issue by Optimox** [mpicbg-csbd/stardist#100]
Hello again,

I'm struggling with visualization of the StarDist3D results.

I would like to export the segmentations to 3D slicer and ideally give a specific color to each cell (based on some metrics I can compute based on rays, dists and points). I can't find the best way to do this, could any one share some useful links?

I could create a dicom file by altering the corresponding pixels myself, but since my 3D images are black and white this would force me to switch to RGB and create huge files.

What would be the best option?

Thank you very much

**Comment by uschmidt83** [comment]
Hi, this is really a generic question and the answer will highly depend on your tool of choice (Fiji, napari, etc.). Hence, it would be best to ask this in the [image.sc forum](https://forum.image.sc/). Note that we are monitoring all questions that use the tag `stardist`.

Best,
Uwe

**Comment by Optimox** [comment]
thank you, I'll do that then!
