### ISSUE TITLE
Unable to install gpu_tools()

### ISSUE THREAD

**Issue by XareniGalindo** [mpicbg-csbd/stardist#101]
I am trying to develop a 3D StarDist model using the Jupyter notebook however I realized my process is running in the CPU instead of the GPU making my the training process run forever. I realized I did not have gup_tools() installed but so far I have not been able to install it. I already try to install it using pip and the developmental version, also I try the troubleshooting suggestions downloading they suggested in the GitHub gputools website (I am not sure if I did this part correctly). Can you help me with what else I can do to run my process in my GPU?

In this case, I am running 3D StarDist without the augmentation process in order to save time during the training but I do not know if this is affecting the speed of the process. I am using the next configuration 

conf = Config3D (
    rays             = rays,
    grid             = grid,
    anisotropy       = anisotropy,
    use_gpu          = use_gpu,
    n_channel_in     = n_channel,
    # adjust for your data below (make patch size as large as possible)
    train_patch_size = (48,96,96),
    train_epochs     = 200,
    train_batch_size = 2,
)

My images are 2 fluorescence stacks of 85 images of size 340x310 pixels plus 2 of the demo images. 

Thank you in advance.

**Comment by uschmidt83** [comment]
Issue is discussed in this [forum thread](https://forum.image.sc/t/training-stardist-with-gputools-support/37344/22), closing here.
