### ISSUE TITLE
Best way to use pretrain model in production?

### ISSUE THREAD

**Issue by Optimox** [mpicbg-csbd/stardist#105]
Hello again,

As I'm a PyTorch user, I'm used to train my models and then export them to a `.jit` format so that I can do the inference without python and only use C++.

Ideally I'd like to have no dependencies on StarDist source code, keras or even python.  Is there a way to do this for a StarDist3D model?

My only use would be to call `model.predict_instances` but as I think this does much more than just forwarding a 3D image to the netwok (tiling + NMS computation) I doubt that it's feasible.

So would you have advice/ good practises to make prediction in a minimal production environment?

Thank you!

**Comment by uschmidt83** [comment]
> Ideally I'd like to have no dependencies on StarDist source code, keras or even python. Is there a way to do this for a StarDist3D model?

I don't think there is. We currently only have StarDist 2D also running Java-based as [a plugin](https://imagej.net/StarDist) in Fiji, but that also requires TensorFlow (and a whole lot of Java libraries).
 
> My only use would be to call `model.predict_instances` but as I think this does much more than just forwarding a 3D image to the netwok (tiling + NMS computation) I doubt that it's feasible.

Yes, the neural network itself could probably be exported in some format to be used by another prediction engine. But the code around it (e.g. tiling) not so easily, especially the NMS, which is written in C++.

> So would you have advice/ good practises to make prediction in a minimal production environment?

I don't really understand your motivation for this. If you want something stable and reproducible, have you considered a Docker container with specific versions of StarDist and all required libraries?

Best,
Uwe

**Comment by Optimox** [comment]
Thank you for your detailed answer.

Yes I considered Docker containers but required some changes in the current production pipeline.
I guess this is definitely the best option.

Thanks again for your help!
Best,
Seb
