### ISSUE TITLE
NMS for multi-class prediction

### ISSUE THREAD

**Issue by trasse** [mpicbg-csbd/stardist#106]
Dear @uschmidt83,
Dear @maweigert,

I have trained multiple stardist model to detect objects.
These objects belong to overlapping classes.

Thus, i need to do an NMS on data from independent predictions.

I know how to get the details by:

labels, details = model.predict_instances...

and the the probabilities from:

coord, points, prob = details['coord'], details['points'], details['prob']

But it is not clear to me :
a) how to transform these into an image (with the probabilities being the pixel values)
b) what is the best way to make an NMS based on 3 pairs of label images & probabilities.

Do you have an example I might look at?

Thanks a lot & Kind regards

Tobias

**Comment by uschmidt83** [comment]
Discussion via email, hence closed here.
