### ISSUE TITLE
"AttributeError: module 'enum' has no attribute 'IntFlag'" during Docker build (solved)

### ISSUE THREAD

**Issue by markemus** [mpicbg-csbd/stardist#108]
I got this error trying to run the docker build using `sudo docker build -t stardist --build-arg NVIDIA_DRIVER_VERSION=455 .`

The solution was to add 

`RUN pip uninstall -y enum34`

to the dockerfile above line 16, meaning above `RUN pip install stardist gputools edt`

After this the build ran successfully.

**Comment by uschmidt83** [comment]
Thanks for letting us know!

I've [updated the Dockerfile](https://github.com/mpicbg-csbd/stardist/commit/a920817035285b31c06e2f6862cb1a384d83f54d) to use a more recent parent container and the problem went away.

Best,
Uwe

**Comment by markemus** [comment]
Hi @uschmidt83 ,

We actually found that we don't have GPU available for Tensorflow after our build- we suspect this is because we used NVIDIA_DRIVER_VERSION=455 (not listed as supported in the README). Will the updated version of tensorflow work with this driver version?

**Comment by uschmidt83** [comment]
> We actually found that we don't have GPU available for Tensorflow after our build

What do you mean? Are you referring to [this problem](https://github.com/NVIDIA/nvidia-docker/issues/1034)?

> we suspect this is because we used NVIDIA_DRIVER_VERSION=455 (not listed as supported in the README).
> Will the updated version of tensorflow work with this driver version?

The variable `NVIDIA_DRIVER_VERSION` is simply used to indicate the name of a package to be installed. If the `docker build` command completed successfully, then it was likely not the issue.

**Comment by uschmidt83** [comment]
Pinging @ksugar, who created the Dockerfile.

**Comment by ksugar** [comment]
@markemus Thanks for reporting this issue. It seems that the problem was caused by the `enum34` module as you pointed out. Similar problems are found [here](https://stackoverflow.com/a/45716067).
Both your solutions should work. Thanks @uschmidt83 for updating [the Dockerfile](https://github.com/mpicbg-csbd/stardist/commit/a920817035285b31c06e2f6862cb1a384d83f54d). I confirmed that only the previous parent image has the `enum34`.

```bash
docker run --rm -it tensorflow/tensorflow:1.13.2-gpu-py3-jupyter /bin/bash -c "pip freeze | grep enum"
enum34==1.1.6

docker run --rm -it tensorflow/tensorflow:1.15.4-gpu-py3-jupyter /bin/bash -c "pip freeze | grep enum"
# no output
```
#### Additional note
`libnvidia-compute-${NVIDIA_DRIVER_VERSION}` is required to use the `gputools` module at runtime.

**Comment by markemus** [comment]
@ksugar thank you for the fix. The new Dockerfile runs without error, and tensorflow installs correctly. 

I still don't have GPU (tf.test.is_gpu_available() returns False), but I'm assuming that it's due to something else I'm doing wrong and I'll open a new issue if I can't figure it out.
