### ISSUE TITLE
WARNING: median object size larger than field of view of the neural network.

### ISSUE THREAD

**Issue by Nal44** [mpicbg-csbd/stardist#109]
Hi All Stardist people,

I did some 3d training that seems to works great, but I always have the message :
WARNING: median object size larger than field of view of the neural network.

I tried to downscale, play with the grid and the patch size but in vain... I always got the message.

For some trainings, even with the error message it was fine but still I would like to understand if possible (personal learning curve).

For example :

```python
median_size = calculate_extents(Y, np.median)
print(median_size)
fov = np.array(model._axes_tile_overlap('ZYX'))
print(fov)
if any(median_size > fov):
    print("WARNING: median object size larger than field of view of the neural network.")

print(median_size) [ 16. 358. 470.]
print(fov) [26 93 93]
WARNING: median object size larger than field of view of the neural network.
```

Images are 16.480.360 (Z.Y.X) dimensions. (I tried with half ... the training found very very tiny objects inside the nucleus ...)

The Objects that I want to detect are nucleus size approx 16 .30.30 (Z.Y.X)

QUESTION : 
What is the median object ? the image itself or the individual nucleus ?
How can I adjust the config/parameters to get rid of this error message ?

Thanks a lot,
Antho
Happy new year !
 

With the following Config : 
```python
Config3D(anisotropy=(29.375, 1.312849162011173, 1.0), axes='ZYXC', backbone='unet', grid=(1, 4, 4), n_channel_in=1, n_channel_out=97, n_dim=3, n_rays=96, net_conv_after_unet=128, net_input_shape=(None, None, None, 1), net_mask_shape=(None, None, None, 1), rays_json={'name': 'Rays_GoldenSpiral', 'kwargs': {'n': 96, 'anisotropy': (29.375, 1.312849162011173, 1.0)}}, train_background_reg=0.0001, train_batch_size=2, train_checkpoint='weights_best.h5', train_checkpoint_epoch='weights_now.h5', train_checkpoint_last='weights_last.h5', train_dist_loss='mae', train_epochs=400, train_foreground_only=0.9, train_learning_rate=0.0003, train_loss_weights=(1, 0.2), train_n_val_patches=None, train_patch_size=(16, 144, 144), train_reduce_lr={'factor': 0.5, 'patience': 40, 'min_delta': 0}, train_steps_per_epoch=100, train_tensorboard=True, unet_activation='relu', unet_batch_norm=False, unet_dropout=0.0, unet_kernel_size=(3, 3, 3), unet_last_activation='relu', unet_n_conv_per_depth=2, unet_n_depth=2, unet_n_filter_base=32, unet_pool=(2, 2, 2), unet_prefix='', use_gpu=True)
{'n_dim': 3,
 'axes': 'ZYXC',
 'n_channel_in': 1,
 'n_channel_out': 97,
 'train_checkpoint': 'weights_best.h5',
 'train_checkpoint_last': 'weights_last.h5',
 'train_checkpoint_epoch': 'weights_now.h5',
 'n_rays': 96,
 'grid': (1, 4, 4),
 'anisotropy': (29.375, 1.312849162011173, 1.0),
 'backbone': 'unet',
 'rays_json': {'name': 'Rays_GoldenSpiral',
  'kwargs': {'n': 96, 'anisotropy': (29.375, 1.312849162011173, 1.0)}},
 'unet_n_depth': 2,
 'unet_kernel_size': (3, 3, 3),
 'unet_n_filter_base': 32,
 'unet_n_conv_per_depth': 2,
 'unet_pool': (2, 2, 2),
 'unet_activation': 'relu',
 'unet_last_activation': 'relu',
 'unet_batch_norm': False,
 'unet_dropout': 0.0,
 'unet_prefix': '',
 'net_conv_after_unet': 128,
 'net_input_shape': (None, None, None, 1),
 'net_mask_shape': (None, None, None, 1),
 'train_patch_size': (16, 144, 144),
 'train_background_reg': 0.0001,
 'train_foreground_only': 0.9,
 'train_dist_loss': 'mae',
 'train_loss_weights': (1, 0.2),
 'train_epochs': 400,
 'train_steps_per_epoch': 100,
 'train_learning_rate': 0.0003,
 'train_batch_size': 2,
 'train_n_val_patches': None,
 'train_tensorboard': True,
 'train_reduce_lr': {'factor': 0.5, 'patience': 40, 'min_delta': 0},
 'use_gpu': True}
```

**Comment by Nal44** [comment]
I found a way to remove the message:
Instead of decreasing the resolution, which end up by detecting very small object due to the FOV issue,  I cropped the images into 800x800 max to 1000x1000 pixels.
That way the objects are found with the right size and the FOV is large than the median object.
Now I have run stardist 3d on brain images and it is very good and the predictions are very good good on new images.

I don't know why it doesn't work in my hands with a reduced resolution but cropping the images works very efficiently.

Hope that helps!
antho

**Comment by maweigert** [comment]
Hi @Nal44 ,

sorry for the late response .

> What is the median object ? the image itself or the individual nucleus ?

It is the median box width (along each of the 3 dimensions) of all ground truth objects that one provides during training. 
So seeing values of 

> print(median_size) [ 16. 358. 470.]

indicates that your objects are very large (in pixel units) and need to be downsampled to fit into the fox. 






> I don't know why it doesn't work in my hands with a reduced resolution but cropping the images works very efficiently.

Actually this should not help (but if it does, I wont complain ;)

**Comment by Nal44** [comment]
Hi @maweigert 
Thanks for the answer,
Then I don't know but it worked well :) .

For Info :
Well without downsampling just by cropping :

median_size = calculate_extents(Y, np.median)
print(median_size)
[16. 77. 83.]

fov = np.array(model._axes_tile_overlap('ZYX'))
print(fov)
[ 20 122 122] 

#I increased the grid to (1,8,8), #

if any(median_size > fov):
    print("WARNING: median object size larger than field of view of the neural network.")

With the following parameters : 
##### 96 is a good default choice (see 1_data.ipynb)
n_rays = 128

# Use OpenCL-based computations for data generator during training (requires 'gputools')
use_gpu = True and gputools_available()

# Predict on subsampled grid for increased efficiency and larger field of view
grid = tuple(1 if a > 1.5 else 2 for a in anisotropy)

# Use rays on a Fibonacci lattice adjusted for measured anisotropy of the training data
rays = Rays_GoldenSpiral(n_rays, anisotropy=anisotropy)

conf = Config3D (
    rays             = rays,
    grid             = (1,8,8),
    anisotropy       = anisotropy,
    use_gpu          = use_gpu,
    n_channel_in     = n_channel,
   backbone='unet',
    unet_n_depth=2,
    
    
    # adjust for your data below (make patch size as large as possible)
#    train_patch_size = (50,250,250),
    train_patch_size = (16,192,192),
    train_batch_size = 4,
   # train_epochs= 100,
  #  train_steps_per_epoch= 50,
)
print(conf)
vars(conf)

**Comment by maweigert** [comment]
Thanks for the info! (just read it :)
