### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY: out of memory

### ISSUE THREAD

**Issue by aligheisari** [mpicbg-csbd/stardist#11]
Hi StarDist team,

After installing StarDist on our cluster and adjusting it to the requirements, there is this error appearing in the terminal while training the model:

> 2019-07-05 15:26:03.689271: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at cwise_ops_common.cc:70 : Resource exhausted: OOM when allocating tensor with shape[64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> 2019-07-05 15:26:03.691201: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 7.67M (8041216 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory"

So far I have tried to modify the notebook to set the GPU memory grows up to 90%: 
```
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.9
session = tf.Session(config=config, ...)
```
which results to other error.
It is highly appreciated if you help me to find a solution.

**Comment by uschmidt83** [comment]
Hi, thank you for trying things out.

Without more details, it's difficult for me to know why you're getting this error. First candidates to check are too large batch and/or patch sizes.

Also, if no other process needs the GPU it's best to not set any memory limits.
In case you do need to do that, I suggest to use the function `limit_gpu_memory` (`from csbdeep.utils.tf import limit_gpu_memory`).

Best,
Uwe

**Comment by aligheisari** [comment]
Hi, sorry for responding late. I was out of office for more than a week.
Actually I am trying to overwrite a limitation on the GPU memory. My aim is to use the 90% or more capacity of the GPU memory
I am trying to run the code to train the model on a cluster which is equipped with GPU. Unfortunately I do not have access to the specifications so far. 
However, I will try also lowering the batch sizes

**Comment by maweigert** [comment]
Closing for now (as it seems to not be related with the code specifically)
