### ISSUE TITLE
Question: Best practice to change Model Backbone and other core changes in the stardist2D?

### ISSUE THREAD

**Issue by caprioGirl** [mpicbg-csbd/stardist#110]
hi there, 
I wanted to know the process of changing the model backbone, for example instead of u-net what if i wanted to incorporate some other neural network? what about other changes in the core? How can i do it? could you please guide me in this regard?

Background Info: everything is running on my part (i.e. training, prediction ) now i want to make some changes in the python code to see how it goes (i.e. i want to build up on your already amazing code)? do i have to make changes in the pip installed package? any best practices to do so ?  Please guide me in this regard! @maweigert @uschmidt83 
THANKYOU

**Comment by uschmidt83** [comment]
Hi, sorry for the late reply. 

The 2D model only supports a `unet` backbone at the moment (cf. [this](https://github.com/mpicbg-csbd/stardist/blob/0c737544a05ae3f6b60667516d2d25e0cebef265/stardist/models/model2d.py#L168-L182)).
The 3D model can use either `unet` or `resnet` backbones (cf. [this](https://github.com/mpicbg-csbd/stardist/blob/0c737544a05ae3f6b60667516d2d25e0cebef265/stardist/models/model3d.py#L205-L228)).

To be honest, we typically find that using a different backbone isn't that important. However, the 3D `unet` backbone (with default parameters) has a bigger receptive field compared to `resnet`.

**Comment by uschmidt83** [comment]
If you want to add a new backbone, you have to update [the config here](https://github.com/mpicbg-csbd/stardist/blob/0c737544a05ae3f6b60667516d2d25e0cebef265/stardist/models/model3d.py#L205-L228), [the function that builds the keras neural network](https://github.com/mpicbg-csbd/stardist/blob/0c737544a05ae3f6b60667516d2d25e0cebef265/stardist/models/model3d.py#L304-L310), and [this function](https://github.com/mpicbg-csbd/stardist/blob/0c737544a05ae3f6b60667516d2d25e0cebef265/stardist/models/model3d.py#L508-L520).

**Comment by wenguanwang123** [comment]
It seems that you did NOT answer the question. The question: after I modified the model code in stardist2D locally, how to import them? Since this package is installed using "pip install ...", the training example in jupiter notebook will import the model from where it is installed, rather than the local directory. 

Please help solve this basic use case of your code.
