### ISSUE TITLE
Model backbone and other changes

### ISSUE THREAD

**Issue by caprioGirl** [mpicbg-csbd/stardist#111]
hi there, 
I wanted to know the process of changing the model backbone, for example instead of u-net how could i incorporate ResNet? or maybe some other model, what about other changes in the model? could you please guide me in this regard?
THANKYOU

**Comment by uschmidt83** [comment]
Hi, sorry for the late reply. 

The 2D model only supports a `unet` backbone at the moment (cf. [this](https://github.com/mpicbg-csbd/stardist/blob/0c737544a05ae3f6b60667516d2d25e0cebef265/stardist/models/model2d.py#L168-L182)).
The 3D model can use either `unet` or `resnet` backbones (cf. [this](https://github.com/mpicbg-csbd/stardist/blob/0c737544a05ae3f6b60667516d2d25e0cebef265/stardist/models/model3d.py#L205-L228)).

To be honest, we typically find that using a different backbone isn't that important. However, the 3D `unet` backbone (with default parameters) has a bigger receptive field compared to `resnet`.
