### ISSUE TITLE
3D training w/ use_gpu=true stops at epoch 1 on Win10

### ISSUE THREAD

**Issue by jboulanger91** [mpicbg-csbd/stardist#112]
Dear all, 
First thanks for the amazing tool! I am having a problem during training using the gpu: when starting the training (which works in CPU mode) it stops at epoch 1/400 using the data-set provided. I don't see any particular error massage in the terminal. 
The CUDA use is stuck at 100% on my task manager so it seems that something is happening ... Has anyone encountered the same problem? 
Thank you very much for your help, 
Jon

**Comment by uschmidt83** [comment]
Hmm, the validation loss is computed at the end of every epoch. Maybe that just takes a while? How long did you wait?

Best,
Uwe

**Comment by jboulanger91** [comment]
Thanks Uwe for replying.  
I got it fixed by replacing the Nvidia GPU Gaming Driver for the Studio Driver (Version 460.89). 
I am running Stardist on Win10, Nvida Geforce GTX 1080.  
Best, 
Jon

**Comment by maweigert** [comment]
Great, thanks for letting us know!
