### ISSUE TITLE
2D extra example

### ISSUE THREAD

**Issue by sinievanderben** [mpicbg-csbd/stardist#114]
Hello! I tried the other 2D example on Jupyter notebook and there is a positional argument missing that is suppose to be there. Not sure whether this is Github issue worthy, but I am not sure from the code on StardistData2D what to fill in. Already tried length = 1 and length = 100*400
![image](https://user-images.githubusercontent.com/47860858/107348595-88bc2580-6ac7-11eb-9d4f-1a3a2e4640b2.png)

**Comment by uschmidt83** [comment]
Hi, thanks for letting us know and sorry for the late reply!

I've just [updated](https://github.com/mpicbg-csbd/stardist/commit/c6f260c0ace1f96c228140b2031261530d6f0aa2) the notebooks (some additional things also needed fixing).

Best,
Uwe
