### ISSUE TITLE
ResourceExhaustedError in predict_function

### ISSUE THREAD

**Issue by MDC91** [mpicbg-csbd/stardist#119]
Hey,
I trained my 3D model and everything worked fine, no errors. Now I want do do the prediction and I get an error I don't understand.

```
img = normalize(X[0], 1,99.8, axis=axis_norm)
labels, details = model.predict_instances(img)

ResourceExhaustedError Traceback (most recent call last)
in
1 img = normalize(X[0], 1,99.8, axis=axis_norm)
----> 2 labels, details = model.predict_instances(img)

~.conda\envs\staining\lib\site-packages\stardist\models\base.py in predict_instances(self, img, axes, normalizer, prob_thresh, nms_thresh, n_tiles, show_tile_progress, verbose, predict_kwargs, nms_kwargs, overlap_label)
417 _shape_inst = tuple(s for s,a in zip(_permute_axes(img).shape, _axes_net) if a != 'C')
418
--> 419 prob, dist = self.predict(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles, show_tile_progress=show_tile_progress, **predict_kwargs)
420 return self._instances_from_prediction(_shape_inst, prob, dist, prob_thresh=prob_thresh, nms_thresh=nms_thresh, overlap_label=overlap_label, **nms_kwargs)
421

~.conda\envs\staining\lib\site-packages\stardist\models\base.py in predict(self, img, axes, normalizer, n_tiles, show_tile_progress, **predict_kwargs)
348
349 else:
--> 350 prob, dist = predict_direct(x)
351
352 prob = resizer.after(prob, axes_net)

~.conda\envs\staining\lib\site-packages\stardist\models\base.py in predict_direct(tile)
314
315 def predict_direct(tile):
--> 316 prob, dist = self.keras_model.predict(tile[np.newaxis], **predict_kwargs)
317 return prob[0], dist[0]
318

~.conda\envs\staining\lib\site-packages\tensorflow\python\keras\engine\training.py in _method_wrapper(self, *args, **kwargs)
128 raise ValueError('{} is not supported in multi-worker mode.'.format(
129 method.name))
--> 130 return method(self, *args, **kwargs)
131
132 return tf_decorator.make_decorator(

~.conda\envs\staining\lib\site-packages\tensorflow\python\keras\engine\training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
1597 for step in data_handler.steps():
1598 callbacks.on_predict_batch_begin(step)
-> 1599 tmp_batch_outputs = predict_function(iterator)
1600 if data_handler.should_sync:
1601 context.async_wait()

~.conda\envs\staining\lib\site-packages\tensorflow\python\eager\def_function.py in call(self, *args, **kwds)
778 else:
779 compiler = "nonXla"
--> 780 result = self._call(*args, **kwds)
781
782 new_tracing_count = self._get_tracing_count()

~.conda\envs\staining\lib\site-packages\tensorflow\python\eager\def_function.py in _call(self, *args, **kwds)
812 # In this case we have not created variables on the first call. So we can
813 # run the first trace but we should fail if variables are created.
--> 814 results = self._stateful_fn(*args, **kwds)
815 if self._created_variables:
816 raise ValueError("Creating variables on a non-first call to a function"

~.conda\envs\staining\lib\site-packages\tensorflow\python\eager\function.py in call(self, *args, **kwargs)
2827 with self._lock:
2828 graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2829 return graph_function._filtered_call(args, kwargs) # pylint: disable=protected-access
2830
2831 @Property

~.conda\envs\staining\lib\site-packages\tensorflow\python\eager\function.py in _filtered_call(self, args, kwargs, cancellation_manager)
1841 args and kwargs.
1842 """
-> 1843 return self._call_flat(
1844 [t for t in nest.flatten((args, kwargs), expand_composites=True)
1845 if isinstance(t, (ops.Tensor,

~.conda\envs\staining\lib\site-packages\tensorflow\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
1921 and executing_eagerly):
1922 # No tape is watching; skip to running the function.
-> 1923 return self._build_call_outputs(self._inference_function.call(
1924 ctx, args, cancellation_manager=cancellation_manager))
1925 forward_backward = self._select_forward_and_backward_functions(

~.conda\envs\staining\lib\site-packages\tensorflow\python\eager\function.py in call(self, ctx, args, cancellation_manager)
543 with _InterpolateFunctionError(self):
544 if cancellation_manager is None:
--> 545 outputs = execute.execute(
546 str(self.signature.name),
547 num_outputs=self._num_outputs,

~.conda\envs\staining\lib\site-packages\tensorflow\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
57 try:
58 ctx.ensure_initialized()
---> 59 tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
60 inputs, attrs, num_outputs)
61 except core._NotOkStatusException as e:

ResourceExhaustedError: OOM when allocating tensor with shape[1,32,100,1024,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
[[node functional_1/conv3d/Conv3D (defined at C:\Users\mdickert.conda\envs\staining\lib\site-packages\stardist\models\base.py:316) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
[Op:__inference_predict_function_691]

Function call stack:
predict_function
```

After checking the issues here, I found out, that I got a warning for the median size:
`median object size: [10. 35. 33.] network field of view : [17 30 30] WARNING: median object size larger than field of view of the neural network.`

Does this has to do something with the error or what do I have to change?

**Comment by MDC91** [comment]
Hey,
I trained my 3D model and everything worked fine, no errors. Now I want do do the prediction and I get an error I don't understand.
`img = normalize(X[0], 1,99.8, axis=axis_norm)
labels, details = model.predict_instances(img)

ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-18-e81e8c0994d6> in <module>
      1 img = normalize(X[0], 1,99.8, axis=axis_norm)
----> 2 labels, details = model.predict_instances(img)

~\.conda\envs\staining\lib\site-packages\stardist\models\base.py in predict_instances(self, img, axes, normalizer, prob_thresh, nms_thresh, n_tiles, show_tile_progress, verbose, predict_kwargs, nms_kwargs, overlap_label)
    417         _shape_inst   = tuple(s for s,a in zip(_permute_axes(img).shape, _axes_net) if a != 'C')
    418 
--> 419         prob, dist = self.predict(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles, show_tile_progress=show_tile_progress, **predict_kwargs)
    420         return self._instances_from_prediction(_shape_inst, prob, dist, prob_thresh=prob_thresh, nms_thresh=nms_thresh, overlap_label=overlap_label, **nms_kwargs)
    421 

~\.conda\envs\staining\lib\site-packages\stardist\models\base.py in predict(self, img, axes, normalizer, n_tiles, show_tile_progress, **predict_kwargs)
    348 
    349         else:
--> 350             prob, dist = predict_direct(x)
    351 
    352         prob = resizer.after(prob, axes_net)

~\.conda\envs\staining\lib\site-packages\stardist\models\base.py in predict_direct(tile)
    314 
    315         def predict_direct(tile):
--> 316             prob, dist = self.keras_model.predict(tile[np.newaxis], **predict_kwargs)
    317             return prob[0], dist[0]
    318 

~\.conda\envs\staining\lib\site-packages\tensorflow\python\keras\engine\training.py in _method_wrapper(self, *args, **kwargs)
    128       raise ValueError('{} is not supported in multi-worker mode.'.format(
    129           method.__name__))
--> 130     return method(self, *args, **kwargs)
    131 
    132   return tf_decorator.make_decorator(

~\.conda\envs\staining\lib\site-packages\tensorflow\python\keras\engine\training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1597           for step in data_handler.steps():
   1598             callbacks.on_predict_batch_begin(step)
-> 1599             tmp_batch_outputs = predict_function(iterator)
   1600             if data_handler.should_sync:
   1601               context.async_wait()

~\.conda\envs\staining\lib\site-packages\tensorflow\python\eager\def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

~\.conda\envs\staining\lib\site-packages\tensorflow\python\eager\def_function.py in _call(self, *args, **kwds)
    812       # In this case we have not created variables on the first call. So we can
    813       # run the first trace but we should fail if variables are created.
--> 814       results = self._stateful_fn(*args, **kwds)
    815       if self._created_variables:
    816         raise ValueError("Creating variables on a non-first call to a function"

~\.conda\envs\staining\lib\site-packages\tensorflow\python\eager\function.py in __call__(self, *args, **kwargs)
   2827     with self._lock:
   2828       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2829     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2830 
   2831   @property

~\.conda\envs\staining\lib\site-packages\tensorflow\python\eager\function.py in _filtered_call(self, args, kwargs, cancellation_manager)
   1841       `args` and `kwargs`.
   1842     """
-> 1843     return self._call_flat(
   1844         [t for t in nest.flatten((args, kwargs), expand_composites=True)
   1845          if isinstance(t, (ops.Tensor,

~\.conda\envs\staining\lib\site-packages\tensorflow\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1921         and executing_eagerly):
   1922       # No tape is watching; skip to running the function.
-> 1923       return self._build_call_outputs(self._inference_function.call(
   1924           ctx, args, cancellation_manager=cancellation_manager))
   1925     forward_backward = self._select_forward_and_backward_functions(

~\.conda\envs\staining\lib\site-packages\tensorflow\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    543       with _InterpolateFunctionError(self):
    544         if cancellation_manager is None:
--> 545           outputs = execute.execute(
    546               str(self.signature.name),
    547               num_outputs=self._num_outputs,

~\.conda\envs\staining\lib\site-packages\tensorflow\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57   try:
     58     ctx.ensure_initialized()
---> 59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:

ResourceExhaustedError:  OOM when allocating tensor with shape[1,32,100,1024,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node functional_1/conv3d/Conv3D (defined at C:\Users\mdickert\.conda\envs\staining\lib\site-packages\stardist\models\base.py:316) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_predict_function_691]

Function call stack:
predict_function`

After checking the issues here, I found out, that I got a warning for the median size:
`median object size:      [10. 35. 33.]
network field of view :  [17 30 30]
WARNING: median object size larger than field of view of the neural network.`

Does this has to do something with the error or what do I have to change?

**Comment by maweigert** [comment]
Hi @MDC91 ,

the error indicates that the stack is too large to be predicted on the GPU in a single pass. This can be fixed by splitting the input into several smaller tiles, predicting each of them, and stitch them back together. All this is can be automatically done by setting the `n_tiles` argument, e.g. like this

```
﻿labels, details = model.predict_instances(img, n_tiles=(1,4,4))
```    

Hope that helps!

M

**Comment by MDC91** [comment]
Unfortunately, this gives me the following error now:

```
img = normalize(X[0], 1,99.8, axis=axis_norm)
labels, details = model.predict_instances(img, n_tiles=(1,4,4))


AttributeError                            Traceback (most recent call last)
~\.conda\envs\staining\lib\site-packages\stardist\models\base.py in _axes_tile_overlap(self, query_axes)
    673         try:
--> 674             self._tile_overlap
    675         except AttributeError:

AttributeError: 'StarDist3D' object has no attribute '_tile_overlap'

During handling of the above exception, another exception occurred:

UnknownError                              Traceback (most recent call last)
<ipython-input-8-dc723ee72fef> in <module>
      1 img = normalize(X[0], 1,99.8, axis=axis_norm)
----> 2 labels, details = model.predict_instances(img, n_tiles=(1,4,4))

~\.conda\envs\staining\lib\site-packages\stardist\models\base.py in predict_instances(self, img, axes, normalizer, prob_thresh, nms_thresh, n_tiles, show_tile_progress, verbose, predict_kwargs, nms_kwargs, overlap_label)
    417         _shape_inst   = tuple(s for s,a in zip(_permute_axes(img).shape, _axes_net) if a != 'C')
    418 
--> 419         prob, dist = self.predict(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles, show_tile_progress=show_tile_progress, **predict_kwargs)
    420         return self._instances_from_prediction(_shape_inst, prob, dist, prob_thresh=prob_thresh, nms_thresh=nms_thresh, overlap_label=overlap_label, **nms_kwargs)
    421 

~\.conda\envs\staining\lib\site-packages\stardist\models\base.py in predict(self, img, axes, normalizer, n_tiles, show_tile_progress, **predict_kwargs)
    320             tiling_axes   = axes_net.replace('C','') # axes eligible for tiling
    321             x_tiling_axis = tuple(axes_dict(axes_net)[a] for a in tiling_axes) # numerical axis ids for x
--> 322             axes_net_tile_overlaps = self._axes_tile_overlap(axes_net)
    323             # hack: permute tiling axis in the same way as img -> x was permuted
    324             n_tiles = _permute_axes(np.empty(n_tiles,np.bool)).shape

~\.conda\envs\staining\lib\site-packages\stardist\models\base.py in _axes_tile_overlap(self, query_axes)
    674             self._tile_overlap
    675         except AttributeError:
--> 676             self._tile_overlap = self._compute_receptive_field()
    677         overlap = dict(zip(
    678             self.config.axes.replace('C',''),

~\.conda\envs\staining\lib\site-packages\stardist\models\base.py in _compute_receptive_field(self, img_size)
    659         z = np.zeros_like(x)
    660         x[(0,)+mid+(slice(None),)] = 1
--> 661         y  = self.keras_model.predict(x)[0][0,...,0]
    662         y0 = self.keras_model.predict(z)[0][0,...,0]
    663         grid = tuple((np.array(x.shape[1:-1])/np.array(y.shape)).astype(int))

~\.conda\envs\staining\lib\site-packages\tensorflow\python\keras\engine\training.py in _method_wrapper(self, *args, **kwargs)
    128       raise ValueError('{} is not supported in multi-worker mode.'.format(
    129           method.__name__))
--> 130     return method(self, *args, **kwargs)
    131 
    132   return tf_decorator.make_decorator(

~\.conda\envs\staining\lib\site-packages\tensorflow\python\keras\engine\training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1597           for step in data_handler.steps():
   1598             callbacks.on_predict_batch_begin(step)
-> 1599             tmp_batch_outputs = predict_function(iterator)
   1600             if data_handler.should_sync:
   1601               context.async_wait()

~\.conda\envs\staining\lib\site-packages\tensorflow\python\eager\def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

~\.conda\envs\staining\lib\site-packages\tensorflow\python\eager\def_function.py in _call(self, *args, **kwds)
    844               *args, **kwds)
    845       # If we did not create any variables the trace we have is good enough.
--> 846       return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
    847 
    848     def fn_with_cond(*inner_args, **inner_kwds):

~\.conda\envs\staining\lib\site-packages\tensorflow\python\eager\function.py in _filtered_call(self, args, kwargs, cancellation_manager)
   1841       `args` and `kwargs`.
   1842     """
-> 1843     return self._call_flat(
   1844         [t for t in nest.flatten((args, kwargs), expand_composites=True)
   1845          if isinstance(t, (ops.Tensor,

~\.conda\envs\staining\lib\site-packages\tensorflow\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1921         and executing_eagerly):
   1922       # No tape is watching; skip to running the function.
-> 1923       return self._build_call_outputs(self._inference_function.call(
   1924           ctx, args, cancellation_manager=cancellation_manager))
   1925     forward_backward = self._select_forward_and_backward_functions(

~\.conda\envs\staining\lib\site-packages\tensorflow\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    543       with _InterpolateFunctionError(self):
    544         if cancellation_manager is None:
--> 545           outputs = execute.execute(
    546               str(self.signature.name),
    547               num_outputs=self._num_outputs,

~\.conda\envs\staining\lib\site-packages\tensorflow\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57   try:
     58     ctx.ensure_initialized()
---> 59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:

UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node functional_1/conv3d/Conv3D (defined at C:\Users\mdickert\.conda\envs\staining\lib\site-packages\stardist\models\base.py:661) ]] [Op:__inference_predict_function_722]

Function call stack:
predict_function
```

Do I maybe have to change something before in the training notebook?
Because after setting 

```
Y_val_pred = [model.predict_instances(x, n_tiles=model._guess_n_tiles(x), show_tile_progress=False)[0]
              for x in tqdm(X_val)]
```

,it gives me no label prediction in the following GT/prediction plot. It's black.

**Comment by maweigert** [comment]
Did you shutdown the training notebook before starting the prediction notebook? Whats the output of `nvidia-smi` right before you start the prediction notebook?

**Comment by MDC91** [comment]
No, I never do.  It's still open. Do I have to close it? I'm really sorry, but I cannot find out, how to run the `nvidia-smi`. I know it was running once, but now I only get the output `nvidia-smi is not recognized as an internal or external command,
operable program or batch file.`.

**Comment by maweigert** [comment]
> No, I never do. It's still open. Do I have to close it? I'm really sorry, but I cannot find out, how to run the `nvidia-smi`. I know it was running once, but now I only get the output `nvidia-smi is not recognized as an internal or external command, operable program or batch file.`.

Tensorflow will reserve all GPU memory available once its first called, so a training notebook that is left open after being run will "occupy" the GPU leaving the prediction notebook with no memory to compute on, which is what you have seen. So shutting down all GPU notebooks before running another one is always recommended. We should add that to the notebook, so thanks for the feedback! :)

       
> ,I get an image without any labeling

Can you post the figure that is produced by this cell?



> when I run `example(model, 0)`, I get the following error:

you need to change `model.predict_instances(img, n_tiles=(1,4,4)` inside the `example` function too

**Comment by MDC91** [comment]
I changed it as you said and it was running, but I get an image without any labels.
So, this is the GT/prediction plot after training:

![training](https://user-images.githubusercontent.com/61161608/109393305-21a0cc80-7921-11eb-94e1-3951b0c9098a.jpg)

and this is what I get then in the prediction:

![prediction](https://user-images.githubusercontent.com/61161608/109393315-3a10e700-7921-11eb-95dc-567ed158d021.jpg)


I annotated the nuclei with the LabKit Plugin in Fiji. I deleted the foreground and background labeling and added for every cell a new label and marked the specific cell in every slice, in which it was visible. I saved this as a .tiff file. In total, I have 160 cells marked in 4 stacks and their associated masks in my train folder. I know it's not the most, but I wanted to look for the outcome first before annotating for days. I hope that was all correctly done.

**Comment by maweigert** [comment]
> So, this is the GT/prediction plot after training:

It seems that in the GT only very few cells are actually annotated - is this true for the training stacks too?

**Comment by MDC91** [comment]
My stacks are quite big and have a lot of nuclei (few thousands), so I tried to annotate different cell shapes in different layers of the brain. As I mentioned, until now its 160 cells in 4 stacks. That's why one only get a few cells annotated in a specific slice. Is this too less, for training and prediction?

**Comment by uschmidt83** [comment]
Hi @MDC91, please read [our FAQ](https://stardist.net/docs/faq.html) before we continue the discussion here.

**Comment by MDC91** [comment]
Okay, that should solve the problem. Should have read that before annotating. Thanks.

**Comment by uschmidt83** [comment]
We're currently updating our documentation to "advertise" the FAQ more prominently, it's currently hard to find...
