### ISSUE TITLE
Integer distances always?

### ISSUE THREAD

**Issue by enfisan** [mpicbg-csbd/stardist#12]
In the file stardist.cpp, when you calculate the distances you always get an integer.
You calculate ```dist = sqrt(x*x + y*y)``` where ```x=n*cos(phi)``` and ```y=n*sin(phi)``` where ```n``` denotes the number of times the loop is reapeted. Therefore
dist =  sqrt(n<sup>2</sup> (cos<sup>2</sup>(phi) + sin<sup>2</sup>(phi))=n sqrt(cos<sup>2</sup>(phi) + sin<sup>2</sup>(phi))=n

 I am not sure if this was intended. 

- In case, it was you can modify the code and just define ```dist=0```  and do `dist++` inside the while loop so that you don't get numerical errors to the calculus of `sin` and `cos`.

- In case, it was not intended and you want to calculate the distance to the pixel you should calculate ` x_hat=round(n*cos(phi))` and  ` y_hat=round(n*sin(phi))` and later define `dist=sqrt(x_hat*x_hat + y_hat*y_hat)`

 For the matrix

[1 0]
[1 1]

for the ray of 45º degrees, currently, you will get the following distances:

[1 0]
[1 1]

while I would expect to get (alternative I propose):

[sqrt(2) 0]
[sqrt(2) sqrt(2)]

It all depends on the case you prefer to have.

**Comment by maweigert** [comment]
Hi @enfisan,

thanks for looking into that!

There are indeed several slightly different ways to calculate the distances (e.g. what you proposed) , but I think as they should have only minor impact on the final stardist result (e.g. as annotation uncertainly typically > 0.5 pixels). But I agree that the code could make that more explicit. Thanks!

**Comment by enfisan** [comment]
Thank you for the reply @maweigert. 
I was using the function to test some morphological operations (not deep learning) based on distances. For my operations I needed the exact l2-distance to the pixel and I was confused why I always got integer distances.

**Comment by maweigert** [comment]
Sure, for your use case it would make sense to do it the way you described, sorry if the code was confusing and thx again for the feedback!
