### ISSUE TITLE
Training runs very slowly

### ISSUE THREAD

**Issue by MDC91** [mpicbg-csbd/stardist#120]
Hey,

so I created in Anaconda a new environment.
I installed python 3.8.5, tensorflow 2.3, stardist 0.6.1, cudatoolkit 10.1 and cudnn 7.6.5.
In jupyter notebook he recognizes the GPU:

```
from tensorflow.python.client import device_lib

def get_available_devices():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos]

print(get_available_devices())

['/device:CPU:0', '/device:XLA_CPU:0', '/device:GPU:0', '/device:XLA_GPU:0']

import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1
```

So, I ran the data script for 3D and the training script and it worked, but it still took 10-11 hours. I have a Nvidia Quadro P6000 and my stacks have 1024x1024 pixel for 100 slices.

After getting an error in the prediction and recognizing, that I got the `WARNING: median object size larger than field of view of the neural network.` error, I changed the grid to (1, 4, 4) instead of (1, 2, 2) and it gives me no error now.
BUT, now the training is running unbelievably slowly and would take days. I have no idea, where the problem could be.
I have set no limit for the GPU use and I tried with `use_gpu = True and False`, but both gave the same slow output.

Any ideas? :/

**Comment by uschmidt83** [comment]
@MDC91, why did you close the issue?

**Comment by MDC91** [comment]
Because the unsophisticated solution to the problem was to just simply restart the whole computer. It still takes almost 10 hours, but I think that's because of my big stacks (100 slices, 1024x1024 pixel). With 'use_gpu =True' it takes around 80s per epoch now.
