### ISSUE TITLE
Different Keras versions

### ISSUE THREAD

**Issue by tamasbalassa** [mpicbg-csbd/stardist#17]
Hey,

I haven't found anything about the required version for Keras, so I wanted to note that I've been thrown an error with Keras v**2.3.0** at the end of the first epoch (_'float' object has no attribute 'item'_ at the line 305 in csbdeep/utils/tf.py).
Forcing Keras version back to **2.2.5** solved the issue.

**Comment by maweigert** [comment]
Hi, 
thanks for the heads up! 
What you describe was indeed a [bug in csbdeep](https://github.com/CSBDeep/CSBDeep/commit/46f362d63923410f32ee6bda24a0c2e1d79ed15c) which `stardist` relies on (triggered by changes in the latest version of `keras`)

By updating `csbdeep` via 

`pip install -U csbdeep`

this issue should be fixed and stardist should work with the latest `keras`.

**Comment by maweigert** [comment]
Should be fixed for `csbdeep>=0.4.1`

**Comment by tamasbalassa** [comment]
Yes, updating both keras (2.2.5 -> 2.3.0) and csbdeep (0.4.0 -> 0.4.1) works well. Thank You!

**Comment by maweigert** [comment]
Great! Thanks again for the feedback!
