### ISSUE TITLE
UnicodeDecodeError during installation

### ISSUE THREAD

**Issue by kapoorlab** [mpicbg-csbd/stardist#18]
Hi Uwe/Martin,

I am trying to install stardist on a CentOS system with python-3.5, keras-2.2.4, tensorflow-1.6.0. I am getting a UnicodeDecode error after trying to install stardist via pip. The error message is the following:

(tensorflowNEW) -bash-4.2$ pip install stardist
Collecting stardist
  Using cached https://files.pythonhosted.org/packages/88/d5/51972b9c6e210a34c44c263a1ac60d525271c5d90a802df5ecc9d66287fa/stardist-0.3.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /data/u934/service_imagerie/v_kapoor/anaconda2/envs/tensorflowNEW/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d3zbl816/stardist/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d3zbl816/stardist/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-d3zbl816/stardist/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d3zbl816/stardist/setup.py", line 46, in <module>
        long_description = f.read()
      File "/data/u934/service_imagerie/v_kapoor/anaconda2/envs/tensorflowNEW/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 769: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by maweigert** [comment]
Hi, 

This seems to be similar like https://github.com/mpicbg-csbd/stardist/issues/16

Could you try if the [link mentioned there](https://github.com/mpicbg-csbd/stardist/issues/16) helps?

**Comment by maweigert** [comment]
Ok, there was indeed an offending non-ascii character. 

If you install the latest version (`stardist 0.3.4`) it should be fixed.

**Comment by kapoorlab** [comment]
Yep that fixed it. Thanks a lot Martin.
