### ISSUE TITLE
anisotropy of training dataset

### ISSUE THREAD

**Issue by wangyuhan01** [mpicbg-csbd/stardist#22]
I am a bit confused with the anisotropy definition in the training configuration. Based on the following command (from the example), it seems to output the training data volume size (ratio) instead the pixel size in xyz. Does isotropy mean the image volume is a cube? or does it mean similar pixel size in xyz? Many thanks! 

extents = calculate_extents(Y)
anisotropy = tuple(np.max(extents) / extents)
print('empirical anisotropy of labeled objects = %s' % str(anisotropy))

**Comment by wangyuhan01** [comment]
Apparently I misunderstood. Sorry about t

**Comment by saskra** [comment]
So what is the answer?

**Comment by wangyuhan01** [comment]
Hi, I only have a vague memory on this as it is from 2 years ago, but I think the anisotropy parameter could be set through Config3D for 3D model training.  My initial question was related with the example notebook (2_training.ipynb), where anisotropy was empirically estimated with image extent.
