### ISSUE TITLE
Qhull warning and errors when doing predictions

### ISSUE THREAD

**Issue by wangyuhan01** [mpicbg-csbd/stardist#23]
I got the following warning and errors during the prediction step. Any idea what this is about and how should I fix it? Many thanks!

Qhull output at end
Qhull precision warning: repartition point p254 from f103 as a outside point above a hidden facet f147 dist 0.00041 nearest vertices 0.2
convex hull of kernel intersection
QH6297 Qhull precision warning: in post-processing (qh_check_maxout) p117 for f306 is 2.3e-10 above hidden facet f833 nearest vertices 5.1e-05
Qhull precision warning: in post-processing (qh_check_maxout) p117 for f306 is 2.3e-10 above hidden facet f833 nearest vertices 5.1e-05
Qhull precision error (qh_check_maxout): large increase in qh.max_outside during post-processing dist 2.3e-10 (107.2x).  See warning QH0032/QH0033.  Disable with 'Q15' (allow_widemax) and 'Pp'
ERRONEOUS FACET:
- f833
    - flags: bottom simplicial tested
    - normal:   -0.8329   0.3488   0.4297
    - offset:    24.8334
    - center: 147.2531166051903 181.6815757347091 80.17435662391317 
    - maxoutside: 2.343867e-10
    - vertices: p127(v191) p126(v155) p34(v69)
    - neighboring facets: f304 f831 f923
    - ridges:
     - r409 tested simplicialbot
           vertices: p126(v155) p34(v69)
           between f304 and f833
     - all ridges: r409 r645
     - r645 tested simplicialtop simplicialbot
           vertices: p127(v191) p34(v69)
           between f833 and f831

While executing: convex hull | qhull 
Options selected for Qhull 2018.0.1.r 2018/12/28:
  run-id 1740914251  _pre-merge  _zero-centrum  _max-width 46
  Error-roundoff 2.7e-13  _one-merge 1.9e-12  _near-inside 9.6e-12
  Visible-distance 5.5e-13  U-max-coplanar 5.5e-13  Width-outside 1.1e-12
  _wide-facet 3.3e-12
Last point added to hull was p38.  Last merge was #361.

At error exit:

Convex hull of 242 points in 3-d:

  Number of vertices: 242
  Number of facets: 124
  Number of non-simplicial facets: 105

Statistics for: convex hull | qhull 

  Number of points processed: 242
  Number of hyperplanes created: 676
  Number of distance tests for qhull: 4560
  Number of distance tests for merging: 7880
  Number of distance tests for checking: 7360
  Number of merged facets: 361
  Maximum distance of merged point above facet: 2.3e-10 (107.4x)
  Maximum distance of merged vertex below facet: -8.3e-13 (0.4x)

**Comment by maweigert** [comment]
Hi @wangyuhan01 ,

Is that error still persisting? And did it actually crash the prediction step (it should not, as QHull errors should be caught, if not that'd be a bug).

**Comment by wangyuhan01** [comment]
The errors are image specific (but do happen often, especially on larger images) and didn't crash the prediction step. What does these errors mean and does this affect the prediction result? Thanks!

**Comment by maweigert** [comment]
> The errors are image specific (but do happen often, especially on larger images) and didn't crash the prediction step. What does these errors mean and does this affect the prediction result?

I guess that happens if polyhedra are too small and/or some vertices are coplanar or don;t give rise to a proper polyhedron. Debugging this is a little involved so for now I always ignored it (never seem to affect the proper polyhedra).
