### ISSUE TITLE
Convert StarDist model to use DeepImageJ

### ISSUE THREAD

**Issue by romainGuiet** [mpicbg-csbd/stardist#28]
Hi @uschmidt83 , Hi @maweigert,

@lacan and I started using [DeepImageJ ](https://github.com/deepimagej) and we encountered a [first issue ](https://github.com/deepimagej/python4deepimagej/issues/2 )while trying to export StarDist model.
Fortunately, @esgomezm helped us and made a [notebook](https://github.com/deepimagej/python4deepimagej/blob/master/export_StarDist_to_TensorFlow_SavedModel.ipynb) to convert the StarDist model, and it works like a charm (see below)!

![image](https://user-images.githubusercontent.com/8309560/69318103-c02d8080-0c3c-11ea-9324-8beb94c60d37.png)

One issue now is that the grid parameter has to be set to (1,1), otherwise the model exported to be DeepImageJ compatible have a downsample output, which creates some weird results (see below).

![image](https://user-images.githubusercontent.com/8309560/69319143-ea803d80-0c3e-11ea-9110-239352d1f3c7.png)

In the training notebook, the grid parameter is set to (2,2), so many people might encounter this problem.

If the grid parameter is set to (2,2), would it be possible to have the output set back to original size? so the model will be fully compatible with DeepImageJ ? 

Thank for your inputs about it,

Best,

Romain

**Comment by maweigert** [comment]
Hi @romainGuiet,

You should be able to get the original shape by simply linearly upscaling the probability and distance prediction by the grid parameter (i.e. two fold along each axis if `grid=(2,2)`). 

Your planning to have the full pipeline (with polygon rendering) as part of a Fiji plugin? 

Cheers,
M

**Comment by uschmidt83** [comment]
> If the grid parameter is set to (2,2), would it be possible to have the output set back to original size? so the model will be fully compatible with DeepImageJ ?

You could modify the TensorFlow model to do the upscaling by `grid` as the final "layer" before exporting the model to be used with DeepImageJ.

Note: The whole point why we predict on a downsampled grid is to save memory (and computation), which can be crucial in 3D.

Cheers,
Uwe

**Comment by uschmidt83** [comment]
> > If the grid parameter is set to (2,2), would it be possible to have the output set back to original size? so the model will be fully compatible with DeepImageJ ?
> 
> You could modify the TensorFlow model to do the upscaling by `grid` as the final "layer" before exporting the model to be used with DeepImageJ.

We added the method [export_TF](https://github.com/mpicbg-csbd/stardist/blob/a41cc99e0010cd36e29a025b8f45858554c027e8/stardist/models/base.py#L521-L548) to the model for this purpose. It will be in the next release.
