### ISSUE TITLE
How to get StarDist ROIs/Labels from DeepImageJ outputs?

### ISSUE THREAD

**Issue by romainGuiet** [mpicbg-csbd/stardist#29]
Hi @uschmidt83 , Hi @maweigert,

When using DeepImageJ, the outputs of the StarDist model are the probability maps and the 32 radial distances ( see solution made @esgomezm  [here](https://github.com/deepimagej/python4deepimagej/issues/2#issuecomment-556073223) )

```
# Input
model_paper.keras_model.input[0]

# Output 1: the object probability (normalized euclidean distance to the nearest background point)
model_paper.keras_model.output[0]

# Output 2: 32 radial distances to the boundary of the object
model_paper.keras_model.output[1]
```

From the StarDist prediction : https://github.com/mpicbg-csbd/stardist/blob/6e7d053bafcf83a6fca47f81469c201b79e993b1/stardist/models/model2d.py#L375

it seems that it would need to get the coord from the distance 
https://github.com/mpicbg-csbd/stardist/blob/6e7d053bafcf83a6fca47f81469c201b79e993b1/stardist/models/model2d.py#L380

then get the points , using proba + coord 
https://github.com/mpicbg-csbd/stardist/blob/6e7d053bafcf83a6fca47f81469c201b79e993b1/stardist/models/model2d.py#L381

to finally get the labels :
https://github.com/mpicbg-csbd/stardist/blob/6e7d053bafcf83a6fca47f81469c201b79e993b1/stardist/models/model2d.py#L383

The goal is to use StarDist in ImageJ and I am wondering if I am on the right path or I missed something obvious that will give me the labels without having to rewrite these functions in groovy?

Furthermore, in a related [issue](https://github.com/mpicbg-csbd/stardist/issues/10#issuecomment-504993401) we were discussing about a StarDist plugin for FIJI. Is it still under development? 
(feel free to close/merge this issue if it's too close to the one mentioned above)

Thank you for your inputs,

Romain

**Comment by maweigert** [comment]
Yes, all these steps would need to be recreated and some of them (non_maximum_supression) are pretty involved and need external libraries (polygon intersection). If I remember correctly @uschmidt83 already managed to have a prototype that works, so his input is probably the most useful.

**Comment by uschmidt83** [comment]
Yes, I have a _very_ rough Fiji plugin that seems to work (2D only).
(It does use CSBDeep to do the network prediction.)

It would probably take me a few weeks (fulltime) to add a GUI, clean it up, and document it. Since I can't work on it fulltime, I don't know how long it is going to take...

Maybe it makes sense to just release the post-processing (including non-maximum suppression) somehow? I'm open to suggestions.

Best,
Uwe

**Comment by esgomezm** [comment]
Hi @uschmidt83

If it helps, until you manage to develop the plugin, in [DeepImageJ ](https://github.com/deepimagej/deepimagej-plugin) it is possible to run a post-processing step after the inference. If you release the post-processing script, any user could include it in the workflow.

Esti

**Comment by uschmidt83** [comment]
Hi @esgomezm, I don't think it's possible to do this is as a simple post-processing script.
We need a separate Java library and ideally multi-threading to make this fast.

PS: I don't think the pre-processing script for StarDist in DeepImageJ is correct, at least when you use it with our pre-trained model. (We do a percentile-based normalization and don't clip values to the 0..1 range.)

Uwe

**Comment by romainGuiet** [comment]
Hi @uschmidt83 , Hi @esgomezm 

My current workaround is to use the **postprocessing.txt** from DeepImageJ to generate the ROIs.
But it's far from being as good as the StarDist roiset output 😢 

Briefly : **Find Maximas > Voronois + Threshold > Math + BinaryMorphoy >Analyse Particles = ROIs**
![image](https://user-images.githubusercontent.com/8309560/70048285-32517e00-15ca-11ea-973a-43923cae0a46.png)

I leave here a [simple code on gist](https://gist.github.com/romainGuiet/250edffa7d07604fb6e575d51abf86cf) if someone else needs it!

Best,
Romain

**Comment by uschmidt83** [comment]
> Yes, I have a _very_ rough Fiji plugin that seems to work (2D only).
> (It does use CSBDeep to do the network prediction.)
> 
> It would probably take me a few weeks (fulltime) to add a GUI, clean it up, and document it. Since I can't work on it fulltime, I don't know how long it is going to take...

We found some time over the holidays to do this: https://imagej.net/StarDist.

> Maybe it makes sense to just release the post-processing (including non-maximum suppression) somehow? I'm open to suggestions.

The plugin also allows to just do the postprocessing, which means you can use DeepImageJ for the prediction if you want.

Best,
Uwe
