### ISSUE TITLE
Obtaining dist and prob maps directly

### ISSUE THREAD

**Issue by GFleishman** [mpicbg-csbd/stardist#36]
Hi Martin and Uwe!

I've trained a 3D model using 32x32x32 voxels patches - and so prediction must occur on patches of that size as well(?). But of course my actual 3D images are much larger. I would like to run the model in parallel on all 32x32x32 patches from my full image with a stride of say 24 voxels along each dimension (so 25% overlap), and then stitch the results back together. It seems like the best objects to stitch would be the probability maps and distance predictions, since they are continuous variables, and then do the NMS afterwards on the entire stitched volume. Does this sound like a reasonable approach? Can you guys provide guidance on modifying the source to obtain these objects directly, rather than just the segments and details, from running predict_instances? Or are they available via another function?

**Comment by maweigert** [comment]
Hi @GFleishman,

> Or are they available via another function?

Provided that you have enough RAM (~100x input image), tiled prediction already is already provided via `model.predict_instances(..., n_tiles = (2,4,4))` which will chop the input images in the respective number of tiles (taking care of overlap etc). You only need to make sure, that the number of tiles is large enough such that a single one fits into GPU memory.

> But of course my actual 3D images are much larger

How large is "large"? If the above doesn't work (as your image is e.g. >2 GB), we currently are implementing tiled predictions for large stacks (where not only prob and dist, but the labels itself are stitched). But this is WIP. 

Hope that helps,

Martin

**Comment by GFleishman** [comment]
Thanks Martin! `n_tiles` looks like exactly what I need. My image isn't that big ~1024x1014x512 voxels. I've noticed the RAM limitation (running on the CPU on my laptop - I'm happy to say though that with like 10 minutes of training on my CPU I already get pretty darn good results!), especially because I used 256 rays. I may stick with the 256 rays but use lots of tiles at prediction time?

**Comment by maweigert** [comment]
> `n_tiles` looks like exactly what I need. My image isn't that big ~1024x1014x512 voxels.

Ok, for that size that indeed should be the way to go!


> (running on the CPU on my laptop - I'm happy to say though that with like 10 minutes of training on my CPU I already get pretty darn good results!

Happy to hear that! Although 10mins on a CPU is like 1 epoch? I would never expect that to work :)

> I may stick with the 256 rays but use lots of tiles at prediction time?

Yes, that'd be an option. Alternatively you could use less rays (I practically never use more than ~96). And again, in the future the RAM limitations should be taken care of by the label tiling  (there is already a branch `big` for that). 

Cheers and thanks for the feedback!

**Comment by GFleishman** [comment]
Maybe it's just my parameterization(?) but with ~10 minutes on my CPU I'm doing 100 epochs at 5 steps_per_epoch; my training patches are 32^3 (so pretty small?), and otherwise my network is just the default resnet I think. It seems like it converges with that limited training as well:

[tensorboard_results_train.pdf](https://github.com/mpicbg-csbd/stardist/files/4277478/tensorboard_results_train.pdf)

[tensorboard_results_validate.pdf](https://github.com/mpicbg-csbd/stardist/files/4277479/tensorboard_results_validate.pdf)

I went with 256 because the plots of IOU over number of rays really saturated there. 128 wasn't too far off, but 64 was at least 0.1 points lower. Maybe part of that is that I'm using a smaller step size for the polygon reconstruction (divided the dx/dy/dz by 4) so maybe it's being more finicky about exactly matching the boundary?

**Comment by maweigert** [comment]
> 32^3 (so pretty small?),

Indeed, that might be the reason for the fast training

> smaller step size for the polygon reconstruction (divided the dx/dy/dz by 4)

You mean `grid=4`?  Together with that small of input size its interesting that it works at all - are your cells that small?

> tensorboard_results_validate.pdf

`prob_loss` looks still pretty bad though - do the results look fine?

**Comment by GFleishman** [comment]
Not grid=4; I was referencing this previous discussion: https://github.com/mpicbg-csbd/stardist/issues/33#issuecomment-583421466
Yeah, 32^3 with grid=4 would be 2^3 patches right?! Definitely too small :)

Qualitatively the results look ok - there are definitely some nuclei missing and very few cells that are just too large. The shape of nuclei is fine, they're all roughly elliptical, but exact boundary matching isn't important to me, if I get 0.6 IOU or better for the majority of cells than I will be very happy.

I don't really know what magnitude of prob_loss would be considered good, I was just looking at the trend. It's so jumpy, it seemed that I had reached the best I could with the data I have - which is rather noisy and was even quite difficult to segment by hand in many places. Qualitatively things look ok (here's a 128x128x128 patch, z-voxels are 2x bigger than x/y voxels hence z dimension looking larger in viewer):

![Screen Shot 2020-03-02 at 3 19 11 PM](https://user-images.githubusercontent.com/8507206/75714224-4d9b5a80-5c99-11ea-9b99-5aad450022bf.png)
![Screen Shot 2020-03-02 at 3 19 42 PM](https://user-images.githubusercontent.com/8507206/75714226-4d9b5a80-5c99-11ea-9d26-28ca0ff1a3cd.png)

I only manually annotated a 128x128x32 patch in a different part of the brain shown above, so it at least generalizes ok to different ROIs of the acquisition and different z-depths. Would you consider manually lowering the learning rate after so many epochs? Or any other recommendations for getting the prob_loss even lower?

**Comment by GFleishman** [comment]
Also - here is what the prob and dists look like for my validation images after 100 epochs of training:

![Screen Shot 2020-03-02 at 3 49 40 PM](https://user-images.githubusercontent.com/8507206/75716613-8a695080-5c9d-11ea-8f6d-fbbb37c25f1b.png)
![Screen Shot 2020-03-02 at 3 49 42 PM](https://user-images.githubusercontent.com/8507206/75716614-8b01e700-5c9d-11ea-9eab-ebd244ccd7d7.png)

**Comment by maweigert** [comment]
> Not grid=4; I was referencing this previous discussion:

Ah, I see :)

> Qualitatively the results look ok - there are definitely some nuclei missing and very few cells that are just too large.

Yep, it's pretty good for that the image have a rather bad SNR and are pretty wild along z! Nice!

> I only manually annotated a 128x128x32 patch

I see. I would try to set `train_patch_size` to the largest possible size (e.g. `(32,128,128)`) to avoid boundary effects. Maybe that will help with the probability. But othe rthan that, your network outputs look reasonable!

> Would you consider manually lowering the learning rate after so many epochs?

That will be done automatically during taring (if the loss saturates), so I wouldn't do that.

**Comment by GFleishman** [comment]
But if I set train_patch_size to (32, 128, 128) doesn't that mean that I only have a single training patch? Right now I'm cutting it up into 32x32x32 patches (randomly choosing the corner of the crop window), and then randomly applying a little augmentation, just 90 degree rotations and axis flips. That way I can go up to like 200 distinct training patches (hopefully covers all the manually annotated region).

**Comment by maweigert** [comment]
> doesn't that mean that I only have a single training patch?

Yes, that would be the case. Although for dense image segmentation it is not really the number of *images* that matters, but the number of *labels* and they scale with the image size (as every pixel is practically a single label). One does therefore not really gain much by subdividing the image (apart from having effectively a smaller batchsize) but might loos something due to the border effect. I would thus suggest using the single full stack and do the flip augmentation on it. Additionally I would shift the intensity globally and add noise for augmentation (to increase robustness). Btw, you can do every augmentation on the fly by providing `augmenter=aug_func` to model.train (where `x2,y2 = aug_func(x,y)` transforms single image/mask pairs).

Hope that helps!
M

**Comment by GFleishman** [comment]
Yep - good suggestions - thanks Martin!

**Comment by GFleishman** [comment]
Hi again - I need to revisit this discussion. I've now moved to my cluster and am trying to run on the full image:
`pred, det = model.predict_instances(image_norm, n_tiles=(2, 16, 8))`
The image is not huge: ~900x1600x300 voxels; but there are _many_ cells, something on the order of 10^5. Whichever part of predict_instances that has the tqdm progress bar finishes in a reasonable amount of time, about 30 minutes, but whatever is after is taking several hours. Due to some network connectivity issues I haven't been able to get through a complete run yet.

I'm guessing the loop monitored by tqdm is model prediction over the tiles, and what comes after is NMS and "polyhedron_to_label"? I guess NMS would scale with the number of voxels, but polyhedron_to_label would scale with the number of labels? Do you have any estimate for how long something like my dataset might take?

**Comment by maweigert** [comment]
> I'm guessing the loop monitored by tqdm is model prediction over the tiles, and what comes after is NMS and "polyhedron_to_label"?

Correct, tqdm only monitors the candidate generation via the CNN, afterwards those candidates get filter by the NMS. For a stack of your size, it should not take that long though. You can check how many candidates are proposed and what the nms progress is by using `predict_instances(...verbose=True)` which should print some info to stdout (if you run it from a notebook it will print it to the calling terminal). Could you check if anything is wrong there? (Eg if there are >>10^6 candidates). 
If that's not good enough, you can test the `big` branch, where improvements for exactly these situations were added (`stardist.big.predict_big`)

**Comment by GFleishman** [comment]
Ok this is running now - had to upgrade to v0.4.1 to get predict_instances with verbose parameter. Just double checking, the NMS and polyhedron_to_label functions do not use anything on the GPU?

**Comment by GFleishman** [comment]
It seems like it is finding a very large number of candidates:

predicting instances with prob_thresh = 0.5430663590930008 and nms_thresh = 0.4
found 7046882 candidates
non-maximum suppression...
Non Maximum Suppression (3D) ++++
NMS: n_polys  = 7046882
NMS: n_rays   = 128
NMS: n_faces  = 252
NMS: thresh   = 0.400
NMS: use_bbox = 1
NMS: using OpenMP with 64 thread(s)
NMS: precompute volumes, bounding boxes, etc
precompute done
NMS: calculated anisotropy: 1.05 	 1.00 	 1.37
NMS: starting suppression loop

According to what I've heard informally about this organism, I only expect about 100,000 nuclei in the entire brain. Would you consider increasing the prob_thresh?

**Comment by maweigert** [comment]
> According to what I've heard informally about this organism, I only expect about 100,000 nuclei in the entire brain. Would you consider increasing the prob_thresh?

Ok, given that your cells are rather small, it could actually be that 7Mio candidates is reasonable and NMS might take longer. Which system are you on? Does NMS uses all available cores?

**Comment by GFleishman** [comment]
Scientific Linux and the scheduler is LSF. I believe the job is using all cores (requested 32; on our system each core comes with a fixed amount of RAM and that's what I needed to accommodate the peak usage), since LSF gives a "Job Efficiency" percentage, which I believe is like a CPU utilization percentage, and it considers all available cores. So I think the job is executing with 64 threads (cores support hyper threading). If there is a better way to check this then I'm happy to.

**Comment by maweigert** [comment]
> The current run has been going for about 3.3 hours and is 38% complete - so I'm hoping for a total runtime of less than 12 hours?

Mhhhm, that sounds a bit excessive. Could you predict on a subset (e.g. 1/2 or 1/4 along each dim) and attach the stdout of NMS (verbose=True)?

**Comment by GFleishman** [comment]
Yep - this is 1/2 size along each axis. Total run time (including data normalization and network evaluation) was about 18 minutes.

Output:
fleishmang@h10u02:test> python ../test_test.py ../../../data/20200116_hucH2BGC7f_hucGal4_UASrgeco_6dpf_green_full_crop_90x110x10.nrrd ./models ./half_crop_pred.nrrd ./half_crop.nrrd
/groups/scicompsoft/home/fleishmang/Python-3.6.4/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
NORMALIZING
PREDICING
WARNING:tensorflow:From /groups/scicompsoft/home/fleishmang/Python-3.6.4/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Loading network weights from 'weights_best.h5'.
2020-03-04 10:03:46.625620: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /misc/lsf/10.1/linux3.10-glibc2.17-x86_64/lib:/groups/scicompsoft/home/fleishmang/bin/py2714/lib:/groups/scicompsoft/home/fleishmang/bin/py2714/lib
2020-03-04 10:03:46.625656: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2020-03-04 10:03:46.625682: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (h10u02.int.janelia.org): /proc/driver/nvidia/version does not exist
2020-03-04 10:03:46.625954: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-04 10:03:46.636682: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2099935000 Hz
2020-03-04 10:03:46.640146: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5af1090 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-04 10:03:46.640168: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Loading thresholds from 'thresholds.json'.
Using default values: prob_thresh=0.543066, nms_thresh=0.4.
image shape:  (430, 838, 150) 	 tiles:  (4, 7, 2)
WARNING:tensorflow:From /groups/scicompsoft/home/fleishmang/Python-3.6.4/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

100%|█████████████████████████████████████████████████████████████████████████████████████████| 56/56 [02:38<00:00,  2.58s/it]
predicting instances with prob_thresh = 0.5430663590930008 and nms_thresh = 0.4
found 1044074 candidates
non-maximum suppression...
Non Maximum Suppression (3D) ++++
NMS: n_polys  = 1044074
NMS: n_rays   = 128
NMS: n_faces  = 252
NMS: thresh   = 0.400
NMS: use_bbox = 1
NMS: using OpenMP with 64 thread(s)
NMS: precompute volumes, bounding boxes, etc
precompute done
NMS: calculated anisotropy: 1.21 	 1.00 	 1.36
NMS: starting suppression loop
|#                                                 | [3 % suppressed]
Qhull output at end
Qhull precision warning: repartition point p252 from f308 as a outside point above a hidden facet f306 dist 1.1e-05 nearest vertices 0.011
|############                                      | [24 % suppressed]
Qhull output at end
Qhull precision warning: repartition point p360 from f420 as a outside point above a hidden facet f334 dist 0.0013 nearest vertices 0.23
|#######################                           | [46 % suppressed]
Qhull output at end
Qhull precision warning: repartition point p328 from f239 as a outside point above a hidden facet f259 dist 0.0017 nearest vertices 0.049
|#################################                 | [66 % suppressed]
Qhull output at end
Qhull precision warning: repartition point p204 from f43 as a outside point above a hidden facet f90 dist 0.0095 nearest vertices 0.22
|###########################################       | [86 % suppressed]
Qhull output at end
Qhull precision warning: repartition point p153 from f65 as a outside point above a hidden facet f271 dist 0.00068 nearest vertices 0.092
|##############################################    | [93 % suppressed]
Qhull output at end
Qhull precision warning: repartition point p41 from f94 as a outside point above a hidden facet f96 dist 0.01 nearest vertices 0.08
|################################################  | [97 % suppressed]
NMS: Function calls:
NMS: ~ bbox+out: 2001551266
NMS: ~ inner:     1380013
NMS: ~ kernel:    1379302
NMS: ~ convex:     444185
NMS: ~ render:     153342
NMS: Excluded intersection:
NMS: + pretest:  2000171253
NMS: + convex:     290843
NMS: Function calls timing:
NMS: / kernel:   6487.08 s  (4.70 ms per call)
NMS: / convex:   2277.00 s  (5.13 ms per call)
NMS: / render:   1567.44 s  (10.22 ms per call)
NMS: Suppressed polyhedra:
NMS: # inner:         711 / 1044074  (0.07 %)
NMS: # kernel:     935117 / 1044074  (89.56 %)
NMS: # render:      87564 / 1044074  (8.39 %)
NMS: # total:     1023392 / 1044074  (98.02 %)
NMS: # keeping      20682 / 1044074  polyhedra (1.98 %)
NMS took 727.1174 s
keeping 20682/1044074 polyhedra
render polygons...
+++++++++++++++ polyhedra to label +++++++++++++++
n_polys           = 20682
n_rays            = 128
n_faces           = 252
nz, ny, nx        = 430 838 150
use_overlap_label = 0
overlap_label     = 0

Since this is 1/8th of the dataset, of the NMS scaled linearly than a runtime of 20mins * 8 = ~2.5 hours would be perfectly fine. The number of polygons does seem to scale linearly, about 1M here and 7.5M for the full image. So NMS must scale super-linearly with the number of polygons, and/or there is something sub-optimal happening on the software side?

**Comment by GFleishman** [comment]
I notice that the first axis of the array is labeled as z - but my data is arranged xyz - x and y have the same voxel sampling rate (0.5189um) and z has larger sampling(1.0um). Is z treated differently in any way?

**Comment by uschmidt83** [comment]
> Did you guys consider any kind of tree structures for increasing the NMS performance?

In 2D, we have an optimization that helps for the (typical) case where the largest object candidate is much smaller in size than the image. We don't have something like that in 3D at the moment.

Using smart data structures would certainly help, but typically makes everything more complicated. So far, it was not the most pressing issue.

As Martin mentioned before, we are close to finishing a new feature that allows predicting on very large images (see [predict_big](https://github.com/mpicbg-csbd/stardist/blob/big/stardist/big.py#L338), work in progress), doing the entire pipeline (including NMS) on overlapping blocks and stitching the results back together.

**Comment by GFleishman** [comment]
Can you give me an idea of how to use the parameters properly? With:

labels, polys, probs = predict_big(model, image_norm, axes='ZYX', tile_size=(128, 128, 128),
                                              min_overlap=(32, 32, 32), context=(40, 40, 40))

I get:


DEBUG:
img.shape = (860, 1676, 301), axes=ZYX, axes_out=ZYX
tile_size = (128, 128, 128), min_overlap=(32, 32, 32), context=(40, 40, 40)

88 70
Traceback (most recent call last):
  File "../test_big.py", line 35, in <module>
    min_overlap=(32, 32, 32), context=(40, 40, 40))
  File "/groups/scicompsoft/home/fleishmang/Python-3.6.4/lib/python3.6/site-packages/stardist-0.4.1-py3.6-linux-x86_64.egg/stardist/big.py", line 373, in predict_big
    tiles = get_tiling(img.shape, axes, tile_size, min_overlap, context, grid)
  File "/groups/scicompsoft/home/fleishmang/Python-3.6.4/lib/python3.6/site-packages/stardist-0.4.1-py3.6-linux-x86_64.egg/stardist/big.py", line 333, in get_tiling
    in  zip(shape, tile_size, min_overlap, context, grid)]
  File "/groups/scicompsoft/home/fleishmang/Python-3.6.4/lib/python3.6/site-packages/stardist-0.4.1-py3.6-linux-x86_64.egg/stardist/big.py", line 332, in <listcomp>
    for _size, _tile_size, _min_overlap, _context, _grid
  File "/groups/scicompsoft/home/fleishmang/Python-3.6.4/lib/python3.6/site-packages/stardist-0.4.1-py3.6-linux-x86_64.egg/stardist/big.py", line 214, in get_tiling
    assert t.slice_write.stop <= t.succ.succ.slice_write.start
AssertionError

Where 88 and 70 are the two values in the <= assertion. Am I doing something wrong?

**Comment by uschmidt83** [comment]
Based on your previous info

> `pred, det = model.predict_instances(image_norm, n_tiles=(2, 16, 8))`
> The image is not huge: ~900x1600x300 voxels;

try this (increase `n_tiles` if you get GPU memory errors):

```python
labels, polys, probs = predict_big(model, image_norm, axes='ZYX', tile_size=(256, 256, 256), min_overlap=32, context=64, n_tiles=(2, 2, 2))
```

> Am I doing something wrong?

That assertion is triggered when tiles overlap not only with their direct neighbors. As mentioned earlier, this is not done and doesn't have proper errors message or documentation.

**Comment by GFleishman** [comment]
Thanks Uwe, this is definitely an improvement, mostly w.r.t. memory usage - it seems like I can now get down to below 15GB of RAM (though I haven't run a job to completion yet). Based on the tqdm estimates, the time will still be quite long, ~8 hours, but using only a single cpu (accessible on my cluster now due to lower RAM requirement) will significantly bring down the cost. Is there any interest in running the tiles in a cluster environment with DASK (or similar)?

**Comment by uschmidt83** [comment]
> Based on the tqdm estimates, the time will still be quite long, ~8 hours, but using only a single cpu (accessible on my cluster now due to lower RAM requirement) will significantly bring down the cost.

Why are you only using a single CPU now? The non-maximum suppression will be much faster with more CPU/cores available.

> Is there any interest in running the tiles in a cluster environment with DASK (or similar)?

We first want to roll out this functionality with a simple API for single-machine use.

Running this in a distributed environment is certainly appealing, but makes everything _much_ more complicated, hence I can't promise you when/if we'll do it. If you have suggestions on how to do this, please tell us.
