### ISSUE TITLE
using cellPose to generate slice-wise ground truth for starDist?

### ISSUE THREAD

**Issue by tischi** [mpicbg-csbd/stardist#38]
Hey guys,

I just tried CellPose and it seems to work really well on 2D data.
I was wondering whether one could use CellPose for ground truth generation to train a 3D StarDist model? What do you think?
https://github.com/MouseLand/cellpose/issues/31

**Comment by uschmidt83** [comment]
Hi @tischi, this isn't really specific to CellPose.

Creating 3D objects from segmented 2D instances is possible by applying some heuristics, and it might work well (or not) depending on the data. I don't think it's a universal approach.
