### ISSUE TITLE
Compilation with GCC 9 fails

### ISSUE THREAD

**Issue by constantinpape** [mpicbg-csbd/stardist#43]
When I compile (or rather pip compiles) with GCC 9, stardist cannot be imported:
```
ImportError: /home/pape/Work/software/conda/miniconda3/envs/antibodies-gpu/lib/python3.7/site-packages/stardist/lib/stardist2d.cpython-37m-x86_64-linux-gnu.so: symbol GOMP_loop_nonmonotonic_dynamic_start, version GOMP_4.5 not defined in file libgomp.so.1
 with link time reference
```
Compiling with GCC 7 works. (Haven't tried any others)

I guess it's not really necessary to fix this, but maybe add something about this in the readme.

**Comment by maweigert** [comment]
Hi @constantinpape ,

thanks for the report. This is probably related to #19 and due to pip using an insufficient libgomp (from conda, without the missing symbol) instead of the system version. Weird.

**Comment by constantinpape** [comment]
> Hi @constantinpape ,
> 
> thanks for the report. This is probably related to #19 and due to pip using an insufficient libgomp (from conda, without the missing symbol) instead of the system version. Weird.

Yes, looks related and seems to be caused by a mismatch of gcc and openmpi.
 I installed it on our cluster, which has an easybuild set-up and I use those compilers.

For the current version, I see the following link:
```
$ ldd stardist2d.cpython-37m-x86_64-linux-gnu.so 
        ....
	libgomp.so.1 => /g/easybuild/x86_64/CentOS/7/skylake/software/GCCcore/8.3.0/lib64/libgomp.so.1 (0x00007f1e8d630000)
        ...
```
So it uses the gcc 8.3 version although I build with gcc 7.3. Anyway, this combination is working, but I am guessing that it fails with gcc 9.

**Comment by constantinpape** [comment]
Ok, I think this is actually not a problem of stardist, but that I compiled it with an invalid setting on our cluster. If I properly load OpenMPI it works.
