### ISSUE TITLE
Where will the predictions be saved after running prediction notebook?

### ISSUE THREAD

**Issue by mballari** [mpicbg-csbd/stardist#45]
Hi,

I trained a StarDist model using my own data, and now I'm trying to run the predictions notebook to test the model using my test images, but I'm having trouble figuring out where the predictions will be saved. Where can I locate the predictions?

- Meg

**Comment by uschmidt83** [comment]
Hi Meg,

the predictions are not automatically saved to disk in our example notebooks.

For example, you can do it like this:

```python
...
labels, details = model.predict_instances(img)

from csbdeep.io import save_tiff_imagej_compatible
axes = 'YX' if labels.ndim==2 else 'ZYX'
save_tiff_imagej_compatible('stardist_result.tif', labels, axes)
```

If you're interested in exporting the ROIs to ImageJ, have a look at [this example](https://nbviewer.jupyter.org/github/mpicbg-csbd/stardist/blob/master/examples/other2D/export_imagej_rois.ipynb).

Best,
Uwe
