### ISSUE TITLE
Cannot find pre-trained model "versatile" from Fiji in `.h5` format 

### ISSUE THREAD

**Issue by VolkerH** [mpicbg-csbd/stardist#46]
Hi,
the Fiji plugin of Stardist comes with two pre-trained models for 2D. 
One is called "Versatile (fluorescent nuclei)", the other is from the DSB.

I cannot find the pre-trained model "Versatile" in this repo here as a `.h5` to use it directly in Python. I looked in my Fiji installation and found a `Model` directory with two `GenericNetwork....` subfolders. I assume these correspond to the two bundled Stardist models (maybe they are from a different plugin altogether), but they are saved in  `.pb` (protocol buffer) format and I'm not sure how to convert them back to the `.h5` used in the example notebooks. 

Apologies if I overlooked something obvious.

**Comment by maweigert** [comment]
Hi @VolkerH ,

Indeed, we haven't added the other pre-trained models yet to the repo (mostly to keep it small). We will add a dedicated API to the stardist package (that can fetch and cache pretrained models explicitly) soon. 

Until then, you can download them here: [_Versatile (fluorescent nuclei)_](https://drive.switch.ch/index.php/s/oCGZJaM949hMzjJ), [_Versatile (H&E nuclei)_](https://drive.switch.ch/index.php/s/LTYaIud7w6lCyuI) 

Hope that helps!
M

**Comment by VolkerH** [comment]
Thank you, Martin !
