### ISSUE TITLE
"TypeError: 'function' object is not iterable"

### ISSUE THREAD

**Issue by mballari** [mpicbg-csbd/stardist#50]
Hi,

I'm a little new to Python and I am trying to run the 2D sample training notebook using the sample data that was provided, but I keep getting the following error shown in the images below, and I'm not sure how to fix it. Can you please help?

Sincerely,
Meg

![image](https://user-images.githubusercontent.com/59752040/80776435-39e46700-8b17-11ea-9e3c-eec1b982fe93.png)
![image](https://user-images.githubusercontent.com/59752040/80776486-5bdde980-8b17-11ea-937f-a5d2e75b5cc1.png)

**Comment by uschmidt83** [comment]
Hi Meg, why did you close the issue?

**Comment by mballari** [comment]
Hi, I closed the issue because I realized that the error occurred after I edited my tensorflow's backend.py file when I got warnings that certain functions were deprecated. I wasn't sure exactly what function I changed that caused the error, so I just reinstalled tensorflow 1.14.0, and that resolved my issue!
