### ISSUE TITLE
Stardist 3D - predictions - The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by pedgomgal1** [mpicbg-csbd/stardist#51]
Hello guys! first congrats for the complete and accesible pipeline that you provide us, people with very few expertise in machine/deep learning. I am trying to predict 3D nuclei images using your Jupyter Notebooks, and I find the kernel died at the line "labels, details = model.predict_instances(img)". 

Before that I trained my own model without problems of compatibility. I used 16 labelled images (400 epochs, 100 steps, path_size = 32, 96 rays, batch_size=1...). With the IoU graph that I have attached.

<img width="901" alt="IoU graph" src="https://user-images.githubusercontent.com/24584817/80805286-e6762580-8bb7-11ea-8de8-be6f26936a31.png">

Well, I would like to test the predictions with this model and maybe later improving the training adding more images for a better accuracy. Anyway, first, I tested your 3D_demo model and later my own model, but both of them give the same error (kernel out).

How could I fix this problem to get the predictions results?

Thank you in advance.

**Comment by maweigert** [comment]
Hi @pedgomgal1 ,

> first congrats for the complete and accesible pipeline that you provide us, people with very few expertise in machine/deep learning.

Thanks! :)

> With the IoU graph that I have attached.

If you look at the accuracy metrics in the left graph, you see that almost all of them are basically zero, i.e. your model a totally wrong output. This might be the reason for the dying kernel too. Did you have a look at `Y_val_pred `? Does that look reasonable? 

So I would first try to see what is going on.

**Comment by pedgomgal1** [comment]
> If you look at the accuracy metrics in the left graph, you see that almost all of them are basically zero, i.e. your model a totally wrong output. This might be the reason for the dying kernel too. Did you have a look at `Y_val_pred `? Does that look reasonable?

Hi, I have solved the kernel problem just tiling the prediction:

Y_val_pred = [model.predict_instances(x, n_tiles=(2,2,2), show_tile_progress=True)

Anyway as you say my model seems to be totally wrong. I don't now why, but the predicted images are super over segmented.

![Screenshot-1](https://user-images.githubusercontent.com/24584817/80838786-16461d00-8bfa-11ea-8b61-2f271c2cbcfd.jpg)

I used these parameters:

{'n_dim': 3,
 'axes': 'ZYXC',
 'n_channel_in': 1,
 'n_channel_out': 129,
 'train_checkpoint': 'weights_best.h5',
 'train_checkpoint_last': 'weights_last.h5',
 'train_checkpoint_epoch': 'weights_now.h5',
 'n_rays': 128,
 'grid': (1, 2, 2),
 'anisotropy': (7.25, 1.0220264317180616, 1.0),
 'backbone': 'resnet',
 'rays_json': {'name': 'Rays_GoldenSpiral',
  'kwargs': {'n': 128, 'anisotropy': (7.25, 1.0220264317180616, 1.0)}},
 'resnet_n_blocks': 4,
 'resnet_kernel_size': (3, 3, 3),
 'resnet_kernel_init': 'he_normal',
 'resnet_n_filter_base': 32,
 'resnet_n_conv_per_block': 3,
 'resnet_activation': 'relu',
 'resnet_batch_norm': False,
 'net_conv_after_resnet': 128,
 'net_input_shape': (None, None, None, 1),
 'net_mask_shape': (None, None, None, 1),
 'train_patch_size': (32, 32, 32),
 'train_background_reg': 0.0001,
 'train_foreground_only': 0.9,
 'train_dist_loss': 'mae',
 'train_loss_weights': (1, 0.2),
 'train_epochs': 400,
 'train_steps_per_epoch': 100,
 'train_learning_rate': 0.0003,
 'train_batch_size': 1,
 'train_n_val_patches': None,
 'train_tensorboard': True,
 'train_reduce_lr': {'factor': 0.5, 'patience': 40, 'epsilon': 0},
 'use_gpu': True}

I have not attached the real truth segmetation but I promise that the masks are perfectly annotated.
Do you have any idea where could I fail? 

Thank you again

**Comment by uschmidt83** [comment]
Hi, the `train_patch_size` used for training is much too small, i.e. the StarDist model "can't see" the shape of an entire nucleus to do a proper prediction. That's why you see the strong oversegmentation.

Please try using `train_patch_size = (32, 192, 192)` or `train_patch_size = (16, 192, 192)`.
If you run into GPU memory issues, try setting `grid = (1, 4, 4)`, or reduce the patch size in x and y in increments of 16 until it fits.

Best,
Uwe

**Comment by pedgomgal1** [comment]
Many thanks @uschmidt83!!!! I had some suspicious about it and you have cleared this doubt. I am trying this new approach, thank you again.

Best wishes,
Pedro

**Comment by pedgomgal1** [comment]
Hi @uschmidt83, from my point this issue can be closed. I followed your advised an after 5 days training, Even the results are not totally perfect, my problem is solved. I got better segmentations:

![picturemessage_0eroha2l pao](https://user-images.githubusercontent.com/24584817/81173549-89f07d00-8fa0-11ea-840c-b9ee7a553dec.png)

I have to increase a bit the patch_size(32,256,256) to get more accurate nuclei segmentations. Anyway the training process is really heavy -> (using GPU) 1 epoch/hour.  (Using CPU) 1 epoch in 1 h 30 mins.  

So, to execute 400 epochs I need more than 2 weeks with the model config that I attached in https://github.com/mpicbg-csbd/stardist/issues/51#issuecomment-622554019, and the updated patch_size.

do you know how could I accelerate the training process without lossing segmentation quality? Thank you again

Best,
Pedro

**Comment by maweigert** [comment]
Hi, 

> Anyway the training process is really heavy -> (using GPU) 1 epoch/hour. (Using CPU) 1 epoch in 1 h 30 mins.

The time difference between CPU and GPU should be way more than this (typically ~30x faster on GPU). Are you sure you are using the GPU (and is it a recent one)?



> I have to increase a bit the patch_size(32,256,256) to get more accurate nuclei segmentations.

How large are your images (e.g. the one you posted before) in pixels? You could addionally try to switch to a U-Net backbone (which will increases the field of view):

```python
Config3D(...

        backbone     = "unet",
        unet_n_depth = 3,
...
)
```

**Comment by pedgomgal1** [comment]
Hi,
I have followed your advise and I changed the Config3D. The time per epoch has improved a 50% (30 min per epoch).

My images could be 1024x1024x70 approximately. But I some of these images the nuclei are larger than 200x200 (XY axes). I have finally decided a patch size=(32,224,224).

My GPU memory is a GeForce GTX 1660 (6GB). I am sure the gpu is working but is expending very few memory during the training:
330MiB /  5936MiB
from this 330MiB, python is only using 144MiB during the training.

I don't know what is the problem. The gputools, tensorflow, MLAEDT-3D, keras, cuda, cudnn...everything is installed and without incompatibilities. Here I attached a PDF with the notebook outputs.

[training_notebook_Pedro.pdf](https://github.com/mpicbg-csbd/stardist/files/4592549/training_notebook_Pedro.pdf)

Best,
Pedro

**Comment by maweigert** [comment]
> from this 330MiB, python is only using 144MiB during the training.

Yes, that is pretty much indicative of tensorflow not using your GPU. Can you check what output the following gives (it should print the name of your GPU)?

```python
import tensorflow as tf  
print(tf.test.gpu_device_name()) 
```

**Comment by pablooriol2** [comment]
Hi there,

My jupyter lab kernel also dies when trying to run stardist on a tiff file :-(

![image](https://user-images.githubusercontent.com/32930813/82265695-82958000-995f-11ea-91bf-414c081bf497.png)

It is very weird because I tried the very same notebook one or two days ago and it did work. I am spawning jupyter from a new conda environment but have double-checked that all required packages are installed. I can import stardist without a problem.

I tried running the same code outside of jupyter but I run into a 'segmentation fault' error.

```
Using TensorFlow backend.
Found model '2D_versatile_fluo' for 'StarDist2D'.
WARNING:tensorflow:From /usr/local/Caskroom/miniconda/base/envs/fretpypeline/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Loading network weights from 'weights_best.h5'.
2020-05-18 23:26:48.105834: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-18 23:26:48.116561: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa9f598b350 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-18 23:26:48.116602: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Loading thresholds from 'thresholds.json'.
Using default values: prob_thresh=0.479071, nms_thresh=0.3.
[1]    2519 segmentation fault  python /usr/local/Caskroom/miniconda/base/envs/fretpypeline/stardist_test.py
```

I don't think I recall seeing the dated messages when it used to work though - could it be related to that? Ie a compiler issue?

Apologies I don't know my way around code much :-/ But a helping hand would be very much appreciated

**Comment by maweigert** [comment]
Hi @pablooriol2 ,

> I tried running the same code outside of jupyter but I run into a 'segmentation fault' error.

Such runtime errors are hard to debug without much context. Could you post a [minimal example](https://en.wikipedia.org/wiki/Minimal_working_example), which reproduces that bug? I.e. a small script+ input data that when called shows above error message. Thanks!

**Comment by pedgomgal1** [comment]
Hi again guys, as I said above. My predictions delayed some weeks due to a bad installion of libraries, promoting a non-recognition of the GPU. Now, I have installed cuda 10.0, cudnn 7.4 and TF 1.13.1 and my GPU is well recognized. 

However a new problem related to the GPU memory allocation has emerged. I have tried different strategies such as reducing the train_path_size to the minimum, reduce the number of images to train to the minimum, grid=(1,4,4), use_gpu='False'...all what you can imagine. Anyway, when the pipeline reach the model training line of code, the program crash. It could be because my GPU memory is not enough [GeForce GTX 1660 (6GB)] to run the program?

Before launch the pipeline:
[0] GeForce GTX 1660 Ti | 47'C,   0 % |    **81 /  5936 MB** | python/48319(71M)

After crashing:
[0] GeForce GTX 1660 Ti | 49'C,   0 % |  **5819 /  5936 MB** | python/48319(71M) python/71346(5738M)

Do you have any idea how could I fix it?I paste the error traceback below:
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-14-cab340fc00c9> in <module>
     13     model = StarDist3D.from_pretrained('3D_demo')
     14 else:
---> 15     model.train(X_trn, Y_trn, validation_data=(X_val,Y_val), augmenter=augmenter)
     16 None;

~/myenv/lib/python3.7/site-packages/stardist/models/model3d.py in train(self, X, Y, validation_data, augmenter, seed, epochs, steps_per_epoch)
    455         Xv, Mv, Pv, Dv = [None]*n_take, [None]*n_take, [None]*n_take, [None]*n_take
    456         for i,k in enumerate(ids):
--> 457             (Xv[i],Mv[i]),(Pv[i],Dv[i]) = _data_val[k]
    458         Xv, Mv, Pv, Dv = np.concatenate(Xv,axis=0), np.concatenate(Mv,axis=0), np.concatenate(Pv,axis=0), np.concatenate(Dv,axis=0)
    459         data_val = [[Xv,Mv],[Pv,Dv]]

~/myenv/lib/python3.7/site-packages/stardist/models/model3d.py in __getitem__(self, i)
     53         arrays = [sample_patches((self.Y[k],) + self.channels_as_tuple(self.X[k]),
     54                                  patch_size=self.patch_size, n_samples=1,
---> 55                                  valid_inds=self.get_valid_inds(k)) for k in idx]
     56 
     57         if self.n_channel is None:

~/myenv/lib/python3.7/site-packages/stardist/models/model3d.py in <listcomp>(.0)
     53         arrays = [sample_patches((self.Y[k],) + self.channels_as_tuple(self.X[k]),
     54                                  patch_size=self.patch_size, n_samples=1,
---> 55                                  valid_inds=self.get_valid_inds(k)) for k in idx]
     56 
     57         if self.n_channel is None:

~/myenv/lib/python3.7/site-packages/stardist/models/base.py in get_valid_inds(self, k, foreground_prob)
    134         else:
    135             patch_filter = (lambda y,p: self.max_filter(y, self.maxfilter_patch_size) > 0) if foreground_only else None
--> 136             inds = get_valid_inds((self.Y[k],)+self.channels_as_tuple(self.X[k]), self.patch_size, patch_filter=patch_filter)
    137             if self.sample_ind_cache:
    138                 _ind_cache[k] = inds

~/myenv/lib/python3.7/site-packages/stardist/models/sample_patches.py in get_valid_inds(datas, patch_size, patch_filter)
     43         patch_mask = np.ones(datas[0].shape,dtype=np.bool)
     44     else:
---> 45         patch_mask = patch_filter(datas[0], patch_size)
     46 
     47     # get the valid indices

~/myenv/lib/python3.7/site-packages/stardist/models/base.py in <lambda>(y, p)
    133             inds = _ind_cache[k]
    134         else:
--> 135             patch_filter = (lambda y,p: self.max_filter(y, self.maxfilter_patch_size) > 0) if foreground_only else None
    136             inds = get_valid_inds((self.Y[k],)+self.channels_as_tuple(self.X[k]), self.patch_size, patch_filter=patch_filter)
    137             if self.sample_ind_cache:

~/myenv/lib/python3.7/site-packages/stardist/models/base.py in <lambda>(y, patch_size)
    105         if self.use_gpu:
    106             from gputools import max_filter
--> 107             self.max_filter = lambda y, patch_size: max_filter(y.astype(np.float32), patch_size)
    108         else:
    109             from scipy.ndimage.filters import maximum_filter

~/myenv/lib/python3.7/site-packages/gputools/convolve/generic_separable_filters.py in max_filter(data, size, res_g, sub_blocks)
    137         _filt = make_filter(_generic_filter_gpu_3d(FUNC = "(val>res?val:res)", DEFAULT = "-INFINITY"))
    138 
--> 139     return _filt(data = data, size = size, res_g = res_g, sub_blocks=sub_blocks)
    140 
    141 

~/myenv/lib/python3.7/site-packages/gputools/convolve/generic_separable_filters.py in _filter(data, size, res_g, sub_blocks)
     86         if isinstance(data, np.ndarray):
     87             if sub_blocks is None or set(sub_blocks) == {1}:
---> 88                 return _filter_numpy(data, size)
     89             else:
     90                 # cut the image into tile and operate on every of them

~/myenv/lib/python3.7/site-packages/gputools/convolve/generic_separable_filters.py in _filter_numpy(data, size)
     78             data = data.astype(np.float32)
     79         data_g = OCLArray.from_array(data)
---> 80         return filter_gpu(data_g = data_g, size=size).get()
     81 
     82     def _filter(data, size=10, res_g=None, sub_blocks=(1, 1, 1)):

~/myenv/lib/python3.7/site-packages/gputools/convolve/generic_separable_filters.py in _filt(data_g, size, res_g)
     64             res_g = OCLArray.empty_like(data_g)
     65 
---> 66         prog.run_kernel("filter_3_x", data_g.shape[::-1], None, data_g.data, res_g.data)
     67         prog.run_kernel("filter_3_y", data_g.shape[::-1], None, res_g.data, tmp_g.data)
     68         prog.run_kernel("filter_3_z", data_g.shape[::-1], None, tmp_g.data, res_g.data)

~/myenv/lib/python3.7/site-packages/gputools/core/oclprogram.py in run_kernel(self, name, global_size, local_size, *args, **kwargs)
     44             self._kernel_dict[name] = getattr(self,name)
     45 
---> 46         self._kernel_dict[name](self._dev.queue,global_size, local_size,*args,**kwargs)
     47 
     48 

~/myenv/lib/python3.7/site-packages/pyopencl/__init__.py in kernel_call(self, queue, global_size, local_size, *args, **kwargs)
    859         # __call__ can't be overridden directly, so we need this
    860         # trampoline hack.
--> 861         return self._enqueue(self, queue, global_size, local_size, *args, **kwargs)
    862 
    863     def kernel_capture_call(self, filename, queue, global_size, local_size,

<generated code> in enqueue_knl_filter_3_x(self, queue, global_size, local_size, arg0, arg1, global_offset, g_times_l, wait_for)

MemoryError: clEnqueueNDRangeKernel failed: MEM_OBJECT_ALLOCATION_FAILURE

**Comment by uschmidt83** [comment]
> However a new problem related to the GPU memory allocation has emerged. I have tried different strategies such as reducing the train_path_size to the minimum, reduce the number of images to train to the minimum, grid=(1,4,4), use_gpu='False'...all what you can imagine. 

Yes, reducing the patch size, increasing grid, *and* setting batch size to 1 are the typical things to try.

> `MemoryError: clEnqueueNDRangeKernel failed: MEM_OBJECT_ALLOCATION_FAILURE`

This problem is due to our OpenCL code not having enough GPU memory during training. It can only occur if `use_gpu='True'`. Use `False` to avoid this problem altogether, but you might pay the price of longer training times if you don't have a powerful multi-core CPU.

Alternatively, you can try to reduce the fraction of memory reserved for TensorFlow from 0.8 to something smaller in our training notebook:

```python
if use_gpu:
    from csbdeep.utils.tf import limit_gpu_memory
    # adjust as necessary: limit GPU memory to be used by TensorFlow to leave some to OpenCL-based computations
    limit_gpu_memory(0.8)
```

> It could be because my GPU memory is not enough [GeForce GTX 1660 (6GB)] to run the program?

More than 6GB would probably make things easier, but you should be able to give it a go by trying the things outlined above.

Best,
Uwe

**Comment by pablooriol2** [comment]
> Hi @pablooriol2 ,
> 
> > I tried running the same code outside of jupyter but I run into a 'segmentation fault' error.
> 
> Such runtime errors are hard to debug without much context. Could you post a [minimal example](https://en.wikipedia.org/wiki/Minimal_working_example), which reproduces that bug? I.e. a small script+ input data that when called shows above error message. Thanks!

Hi @maweigert ,

Unfortunately, here I am again. Apologies for not replying back; reason was that I managed to fix it... And stupid me I didn't note down what I did to fix it. Anyways... I was just re-testing a script and was initially getting a Java runtime error that made python crash, but this error was only coming up when I was trying to do segmentation with StarDist. So I decided to run stardist on a tif file without a starting a Java VM and surprise surprise, I'm getting pretty much the same error as previously posted; segmentation fault.

I am now attaching a short script, a tiff file (both in .zip file below) and the output (below) that I get when running said script.

Output:
```
Using TensorFlow backend.
Found model '2D_versatile_fluo' for 'StarDist2D'.
WARNING:tensorflow:From /usr/local/Caskroom/miniconda/base/envs/third1/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From /usr/local/Caskroom/miniconda/base/envs/third1/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4070: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

Loading network weights from 'weights_best.h5'.
2020-07-19 13:07:19.812849: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-19 13:07:19.827911: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fcdf7616980 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-19 13:07:19.827930: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Loading thresholds from 'thresholds.json'.
Using default values: prob_thresh=0.479071, nms_thresh=0.3.
WARNING:tensorflow:From /usr/local/Caskroom/miniconda/base/envs/third1/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

[1]    71664 segmentation fault  python stardist_test2.py
```

[stardist_test.zip](https://github.com/mpicbg-csbd/stardist/files/4943684/stardist_test.zip)

Let me know if you can run it and whether you might have any idea how to address is. My whole image analysis pipeline depends on this xD so I'd highly appreciate any pointers/help

**Comment by pablooriol2** [comment]
Glad to report that making a new environment is a workaround solution but doesn't directly fix the issue itself.

A bit annoying since I have to install quite a few other packages manually, but at least StarDist is working so we're all good :P

If this occurs more often than not though, then it definitely needs to be addressed directly, otherwise it's not viable. I'll keep you posted..
