### ISSUE TITLE
Issue importing StarDist into Python/Jupyter

### ISSUE THREAD

**Issue by pablooriol2** [mpicbg-csbd/stardist#56]
Hi!

I get the following error when trying to import modules from stardist.

`ImportError: dlopen(/usr/local/Caskroom/miniconda/base/envs/tf/lib/python3.7/site-packages/stardist/lib/stardist2d.cpython-37m-darwin.so, 2): Symbol not found: _GOMP_loop_nonmonotonic_dynamic_next
  Referenced from: /usr/local/Caskroom/miniconda/base/envs/tf/lib/python3.7/site-packages/stardist/lib/stardist2d.cpython-37m-darwin.so
  Expected in: flat namespace
 in /usr/local/Caskroom/miniconda/base/envs/tf/lib/python3.7/site-packages/stardist/lib/stardist2d.cpython-37m-darwin.so`

I have followed the installation steps as per the guidelines.

Anyone have any idea how to fix this issue?

**Comment by maweigert** [comment]
Seem related/identical to https://github.com/mpicbg-csbd/stardist/issues/19#issuecomment-535610758. So try whether the solution given there works for you...

**Comment by pablooriol2** [comment]
Hi @maweigert,
Thanks so much for your help. That thread was really helpful.
I had some extra changes (namely _libstdc++.6.dylib_ & _libgcc_s.1.dylib_) that needed to be done though, but thanks to the issue you pointed to I knew how to. I can now import StarDist in Python. Cheers!

```
(tf) {22:05}~ ➭ DYLD_PRINT_LIBRARIES=1 python -c "import stardist;" 2>&1 | grep libgomp
dyld: loaded: <22ED9F19-4E51-32C1-8BA4-EE6B38D4E60A> /usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/libgomp.1.dylib
dyld: unloaded: <22ED9F19-4E51-32C1-8BA4-EE6B38D4E60A> /usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/libgomp.1.dylib
(tf) {22:06}~ ➭ otool -L /usr/local/Caskroom/miniconda/base/envs/tf/lib/python3.7/site-packages/stardist/lib/stardist2d.cpython-37m-darwin.so
/usr/local/Caskroom/miniconda/base/envs/tf/lib/python3.7/site-packages/stardist/lib/stardist2d.cpython-37m-darwin.so:
	@rpath/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.19.0)
	/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/usr/local/Caskroom/miniconda/base/envs/tf/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by maweigert** [comment]
> I had some extra changes (namely _libstdc++.6.dylib_ & _libgcc_s.1.dylib_) that needed to be done though, but thanks to the issue you pointed to I knew how to.

Great to hear! Could you quickly post what these extra changes were (that way other with the same issue would find a solution)? Thanks!

**Comment by pablooriol2** [comment]
Sure!

I can't show what the 'faulty configuration' as it's been fixed already, but essentially I had two files (those aforementioned) whose location had to be changed in the 'settings'. So I did the following:

First I proceeded to change the 'location settings' of the **_libstdc++.6.dylib_** file.
 ```
1225  otool -L /usr/local/Caskroom/miniconda/base/envs/tf/lib/python3.7/site-packages/stardist/lib/stardist2d.cpython-37m-darwin.so
 1226  src="@rpath/libstdc++.6.dylib"
 1227  dst="/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/libstdc++.6.dylib"
 1228  install_name_tool -change ${src} ${dst} /usr/local/Caskroom/miniconda/base/envs/tf/lib/python3.7/site-packages/stardist/lib/stardist2d.cpython-37m-darwin.so
 1229  install_name_tool -change ${src} ${dst} /usr/local/Caskroom/miniconda/base/envs/tf/lib/python3.7/site-packages/stardist/lib/stardist3d.cpython-37m-darwin.so
```

Then, I checked again and changed 'location settings' of the **_libgcc_s.1.dylib_** file.
```
 1230  otool -L /usr/local/Caskroom/miniconda/base/envs/tf/lib/python3.7/site-packages/stardist/lib/stardist2d.cpython-37m-darwin.so
 1231  src="/usr/local/Caskroom/miniconda/base/envs/tf/lib/libgcc_s.1.dylib"
 1232  dst="/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/libgcc_s.1.dylib"
 1233  install_name_tool -change ${src} ${dst} /usr/local/Caskroom/miniconda/base/envs/tf/lib/python3.7/site-packages/stardist/lib/stardist2d.cpython-37m-darwin.so
 1234  install_name_tool -change ${src} ${dst} /usr/local/Caskroom/miniconda/base/envs/tf/lib/python3.7/site-packages/stardist/lib/stardist3d.cpython-37m-darwin.so
```

Finally, I end up with this (working) configuration:

```
otool -L /usr/local/Caskroom/miniconda/base/envs/tf/lib/python3.7/site-packages/stardist/lib/stardist2d.cpython-37m-darwin.so
/usr/local/Caskroom/miniconda/base/envs/tf/lib/python3.7/site-packages/stardist/lib/stardist2d.cpython-37m-darwin.so:
	/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.19.0)
	/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

Essentially, I changed all (except libSystem.B.dylib) gcc-related .dylib file locations from local (ie your environment) to base → check src & dst to see what I mean.

Hope this was helpful/useful :-)

**Comment by maweigert** [comment]
Great, thanks!
