### ISSUE TITLE
More Build Issues on Mac

### ISSUE THREAD

**Issue by kapoorlab** [mpicbg-csbd/stardist#58]
HI there,

I was trying to update stardist to the latest version on my Mac and am running into problems. The problem is coming from numba while I imported stardist:
```
----> 6 from numba.utils import total_ordering
      7 
      8 

ImportError: cannot import name 'total_ordering'
```
To get updated stardist I did:

```
 conda install -c conda-forge gcc
CC=gcc-9 CXX=g++-9 pip install stardist --ignore-installed
```
It installs without issue but when I try to run the notebook with stardist import numba fails so I tried to pip install numba again but that does not solves this issue.

gcc versions:
gcc-8 (Homebrew GCC 8.4.0_1) 8.4.0
gcc-9 (Homebrew GCC 9.3.0) 9.3.0

pip install stardist message:
```
Successfully installed PyWavelets-1.1.1 csbdeep-0.5.1 cycler-0.10.0 decorator-4.4.2 h5py-2.10.0 imageio-2.8.0 keras-2.3.1 keras-applications-1.0.8 keras-preprocessing-1.1.2 kiwisolver-1.2.0 llvmlite-0.32.1 matplotlib-3.2.1 networkx-2.4 numba-0.49.1 numpy-1.18.4 pillow-7.1.2 pyparsing-2.4.7 python-dateutil-2.8.1 pyyaml-5.3.1 scikit-image-0.17.2 scipy-1.4.1 setuptools-47.1.1 six-1.15.0 stardist-0.5.0 tifffile-2020.5.25 tqdm-4.46.0
```

**Comment by uschmidt83** [comment]
I don't know why this happens, but have you tried uninstalling StarDist and numba before installing StarDist?

**Comment by kapoorlab** [comment]
Yeah, instead of doing --ignore-installed, uninstalling stardist n associated libraries and then doing a fresh install worked. Thanks.
