### ISSUE TITLE
'axes do not match array' during quick demo on RGB images

### ISSUE THREAD

**Issue by asasama12** [mpicbg-csbd/stardist#59]
I was able to successfully run the 2D segmentation demo, but when I swapped out the images for my own RGB histology images, I get an error during the random_fliprot function.  I assume the demo is written for grayscale images but how do I adapt it for color?  Or should I just convert to grayscale before using the stardist? 

```python
<ipython-input-22-72eaa5608f65> in random_fliprot(img, mask)
      3     perm = np.random.permutation(axes)
      4     img = img.transpose(perm)
----> 5     mask = mask.transpose(perm)
      6     for ax in axes:
      7         if np.random.rand() > 0.5:

ValueError: axes don't match array
```

**Comment by asasama12** [comment]
When I used grayscale images I got a different error during .optimizethresholds: 

~/tensor_env/lib/python3.6/site-packages/stardist/models/base.py in _guess_n_tiles(self, img)
    471 
    472     def _guess_n_tiles(self, img):
--> 473         axes = self._normalize_axes(img, axes=None)
    474         shape = list(img.shape)
    475         if 'C' in axes:

~/tensor_env/lib/python3.6/site-packages/stardist/models/base.py in _normalize_axes(self, img, axes)
    489                 # img has no dedicated channel axis, but 'C' always part of config axes
    490                 axes = axes.replace('C','')
--> 491         return axes_check_and_normalize(axes, img.ndim)
    492 
    493 

~/tensor_env/lib/python3.6/site-packages/csbdeep/utils/utils.py in axes_check_and_normalize(axes, length, disallowed, return_allowed)
    193     disallowed is None or consume(a not in disallowed or _raise(ValueError("disallowed axis '%s'."%a)) for a in axes)
    194     consume(axes.count(a)==1 or _raise(ValueError("axis '%s' occurs more than once."%a)) for a in axes)
--> 195     length is None or len(axes)==length or _raise(ValueError('axes (%s) must be of length %d.' % (axes,length)))
    196     return (axes,allowed) if return_allowed else axes
    197 

~/tensor_env/lib/python3.6/site-packages/csbdeep/utils/utils.py in _raise(e)
     86 
     87 def _raise(e):
---> 88     raise e
     89 
     90 

ValueError: axes (YXC) must be of length 2.

**Comment by maweigert** [comment]
> I assume the demo is written for grayscale images but how do I adapt it for color?

yes, we only recently adapted the notebooks to work with RGB/multi-channel images as well. This is currently available only in the `dev` branch, so you can use the [respective training notebook](https://github.com/mpicbg-csbd/stardist/blob/dev/examples/2D/2_training.ipynb) (or just checkout the branch).
