### ISSUE TITLE
'Name Error' generated by cell 4 of Stardist 2D example notebook

### ISSUE THREAD

**Issue by liecuass** [mpicbg-csbd/stardist#64]
Hello, 

Thanks for creating stardist I am very excited to try it. I have worked through the installation on mac OS, thank you for documenting known issues these were needed for getting the installation working. 

I am new to python, and am using the examples provided to check the stardist installation on my system. In the training example for 2D workflows (https://nbviewer.jupyter.org/github/mpicbg-csbd/stardist/blob/master/examples/2D/2_training.ipynb) 

I have the following error when I run cell 4. 

**Error Message when running cell 4: Name Error**
```python

NameError                                 Traceback (most recent call last)
<ipython-input-4-60fa9a7f6670> in <module>
      5     sys.stdout.flush()
      6 
----> 7 X = [normalize(x,1,99.8,axis=axis_norm) for x in tqdm(X)]
      8 Y = [fill_label_holes(y) for y in tqdm(Y)]

<ipython-input-4-60fa9a7f6670> in <listcomp>(.0)
      5     sys.stdout.flush()
      6 
----> 7 X = [normalize(x,1,99.8,axis=axis_norm) for x in tqdm(X)]
      8 Y = [fill_label_holes(y) for y in tqdm(Y)]

NameError: name 'normalize' is not defined
```

The code that generates the error is:

**Code in cell 4**
```python
axis_norm = (0,1)   # normalize channels independently
# axis_norm = (0,1,2) # normalize channels jointly
if n_channel > 1:
    print("Normalizing image channels %s." % ('jointly' if axis_norm is None or 2 in axis_norm else 'independently'))
    sys.stdout.flush()

X = [normalize(x,1,99.8,axis=axis_norm) for x in tqdm(X)]
Y = [fill_label_holes(y) for y in tqdm(Y)]
```

**Attempted fix**

The cell runs without an error if I comment out the following line:
```
#X = [normalize(x,1,99.8,axis=axis_norm) for x in tqdm(X)]
```
I also wondered if "normalize" needed the sci-kit learn package before the function and tried:

```python
import numpy as np
from sklearn.preprocessing import normalize

axis_norm = (0,1)   # normalize channels independently
# axis_norm = (0,1,2) # normalize channels jointly
if n_channel > 1:
    print("Normalizing image channels %s." % ('jointly' if axis_norm is None or 2 in axis_norm else 'independently'))
    sys.stdout.flush()

X = [normalize(x,1,99.8,axis=axis_norm) for x in tqdm(X)]
Y = [fill_label_holes(y) for y in tqdm(Y)]

```
But I think my idea is completely wrong as this gives a type error:
```python
TypeError                                 Traceback (most recent call last)
<ipython-input-16-a4b6b81a1f5e> in <module>
      8     sys.stdout.flush()
      9 
---> 10 X = [normalize(x,1,99.8,axis=axis_norm) for x in tqdm(X)]
     11 Y = [fill_label_holes(y) for y in tqdm(Y)]

<ipython-input-16-a4b6b81a1f5e> in <listcomp>(.0)
      8     sys.stdout.flush()
      9 
---> 10 X = [normalize(x,1,99.8,axis=axis_norm) for x in tqdm(X)]
     11 Y = [fill_label_holes(y) for y in tqdm(Y)]

TypeError: normalize() got multiple values for argument 'axis'

```

**Summary**
Could you please suggest the fix to this Name Error message, and apologies for what is surely a naive question!

**Comment by uschmidt83** [comment]
Thanks for trying StarDist!

> **Error Message when running cell 4: Name Error**

The `normalize` function should've been imported in the very first cell of [that notebook](https://nbviewer.jupyter.org/github/mpicbg-csbd/stardist/blob/master/examples/2D/2_training.ipynb):
```python
from csbdeep.utils import Path, normalize
```

**Comment by liecuass** [comment]
Thank you! I fixed the first cell, and the rest of the notebook completed.
