### ISSUE TITLE
Keras version limit

### ISSUE THREAD

**Issue by Czaki** [mpicbg-csbd/stardist#65]
Current keras release does not support TensorFlow 1.x. It looks like last version which support tf 1.x is 2.3.0. 

Maybe add this information to documentation

**Comment by uschmidt83** [comment]
Thanks for the info, we noticed that too. We've just made a new release of [CSBDeep](https://github.com/CSBDeep/CSBDeep) (which StarDist depends on), now enforcing a version of Keras below 2.4.

**Comment by Czaki** [comment]
Ok. So is install stardist a little to early. 

It is force tensorflow version also?

**Comment by uschmidt83** [comment]
> It is force tensorflow version also?

No, as written in the documentation you  have to install TensorFlow 1.x beforehand. For example:
```
pip install 'tensorflow<2'
pip install stardist
```

**Comment by Czaki** [comment]
Ok. thanks
