### ISSUE TITLE
why norm by row?

### ISSUE THREAD

**Issue by ucasiggcas** [mpicbg-csbd/stardist#73]
hi,dear
In the [line](https://github.com/mpicbg-csbd/stardist/blob/5359846a92ca466f07999f9efdb0fcc66ff4c3c5/stardist/geometry/geom3d.py#L308), 
```
    scaled_verts = scale*rays_vertices
    scaled_verts /= np.linalg.norm(scaled_verts,axis = 1, keepdims=True)
```
if every column is the feature, why you norm by row ?
confused ahout that, should be the down ??
```
    scaled_verts = scale*rays_vertices
    scaled_verts /= np.linalg.norm(scaled_verts,axis = 0, keepdims=True)
```
could you pls help me ?
thx

**Comment by maweigert** [comment]
Hi, 

the vertiex array has shape `(n_verts,3)`, with the rows being the 3 cartesian coordinates. As we want to norm each vertex vector to unity norm, we need to divide by the norm compute over the last (row) axis. 
Hope that helps,
M
