### ISSUE TITLE
3D utility in current release (0.6.0)

### ISSUE THREAD

**Issue by jiahaoh** [mpicbg-csbd/stardist#77]
Dear All,

First of all, I really appreciate the wonderful work, and thank you guys for very active development efforts. I saw there is a new release of the StarDist package. So I have two questions related to the 0.6.0 version:

1. For 3D model training, there is a note in the "README.md" saying " you might experience improved performance during training by installing MLAEDT-3D". How should we use the EDT package during the training process or it is automatically utilized by StarDist?

2. For 3D prediction export, I would like to try the new function to export 3D results as .obj file (OBJ geometry format). However, I did not find related functions in the code. Please let me know what is the correct way to test that.

Best,

Jiahao

**Comment by uschmidt83** [comment]
Hi Jiahao,

> First of all, I really appreciate the wonderful work, and thank you guys for very active development efforts.

Thanks!

> 1. For 3D model training, there is a note in the "README.md" saying " you might experience improved performance during training by installing MLAEDT-3D". How should we use the EDT package during the training process or it is automatically utilized by StarDist?

It's automatically used when the package is installed. (See code [here](https://github.com/mpicbg-csbd/stardist/blob/afe731be6ce618c9129d58029488da880603a735/stardist/utils.py#L50-L57).)

> 2. For 3D prediction export, I would like to try the new function to export 3D results as .obj file (OBJ geometry format). However, I did not find related functions in the code. Please let me know what is the correct way to test that.

The function is [`export_to_obj_file3D`](https://github.com/mpicbg-csbd/stardist/blob/afe731be6ce618c9129d58029488da880603a735/stardist/geometry/geom3d.py#L276-L346) and can be imported from `stardist.geometry`. Also see a usage example [here](https://github.com/mpicbg-csbd/stardist/blob/afe731be6ce618c9129d58029488da880603a735/tests/test_model3D.py#L148-L157).

Best,
Uwe
