### ISSUE TITLE
Installation Error: "Could not build wheels for stardist which use PEP 517 and cannot be installed directly"

### ISSUE THREAD

**Issue by TMM-98** [mpicbg-csbd/stardist#79]
failed to install Star Dist via the CC=gcc-9 CXX=g+±9 pip install stardist command. The Error output is below.
I have followed the instructions on https://github.com/mpicbg-csbd/stardist thoroughly and should have all the prerequisites installed.

Any solutions? Thank you so much!

Thiemo Moellenkamp

thiemomoellenkamp@Thiemos-MacBook-Pro ~ % brew install gcc
Warning: gcc 10.2.0 is already installed and up-to-date
To reinstall 10.2.0, run `brew reinstall gcc`

thiemomoellenkamp@Thiemos-MacBook-Pro ~ % CC=gcc-9 CXX=g++-9 pip install stardist
Collecting stardist
  Using cached stardist-0.6.0.tar.gz (407 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting scikit-image
  Using cached scikit_image-0.17.2-cp38-cp38-macosx_10_13_x86_64.whl (12.2 MB)
Collecting numba
  Using cached numba-0.50.1-cp38-cp38-macosx_10_14_x86_64.whl (2.1 MB)
Collecting csbdeep>=0.6.0
  Using cached csbdeep-0.6.0-py2.py3-none-any.whl (67 kB)
Collecting matplotlib!=3.0.0,>=2.0.0
  Using cached matplotlib-3.3.0-1-cp38-cp38-macosx_10_9_x86_64.whl (11.4 MB)
Requirement already satisfied: scipy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scikit-image->stardist) (1.4.1)
Requirement already satisfied: numpy>=1.15.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scikit-image->stardist) (1.18.5)
Collecting pillow!=7.1.0,!=7.1.1,>=4.3.0
  Using cached Pillow-7.2.0-cp38-cp38-macosx_10_10_x86_64.whl (2.2 MB)
Collecting networkx>=2.0
  Using cached networkx-2.4-py3-none-any.whl (1.6 MB)
Collecting imageio>=2.3.0
  Using cached imageio-2.9.0-py3-none-any.whl (3.3 MB)
Collecting PyWavelets>=1.1.1
  Using cached PyWavelets-1.1.1-cp38-cp38-macosx_10_9_x86_64.whl (4.3 MB)
Collecting tifffile>=2019.7.26
  Using cached tifffile-2020.7.24-py3-none-any.whl (146 kB)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from numba->stardist) (47.1.0)
Collecting llvmlite<0.34,>=0.33.0.dev0
  Using cached llvmlite-0.33.0-cp38-cp38-macosx_10_9_x86_64.whl (17.3 MB)
Collecting keras<2.4,>=2.1.2
  Using cached Keras-2.3.1-py2.py3-none-any.whl (377 kB)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from csbdeep>=0.6.0->stardist) (1.15.0)
Requirement already satisfied: h5py in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from csbdeep>=0.6.0->stardist) (2.10.0)
Collecting tqdm
  Using cached tqdm-4.48.1-py2.py3-none-any.whl (68 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0-cp38-cp38-macosx_10_9_x86_64.whl (60 kB)
Collecting decorator>=4.3.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting keras-applications>=1.0.6
  Using cached Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from keras<2.4,>=2.1.2->csbdeep>=0.6.0->stardist) (1.1.2)
Processing ./Library/Caches/pip/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c/PyYAML-5.3.1-cp38-cp38-macosx_10_9_x86_64.whl
Building wheels for collected packages: stardist
  Building wheel for stardist (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/th/04d371mj4mgdzrv6rv0wn7v00000gn/T/tmpzi52ehoe
       cwd: /private/var/folders/th/04d371mj4mgdzrv6rv0wn7v00000gn/T/pip-install-3coajrkc/stardist
  Complete output (54 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/version.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/rays3d.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/sample_patches.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/nms.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/matching.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/utils.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  copying stardist/big.py -> build/lib.macosx-10.9-x86_64-3.8/stardist
  creating build/lib.macosx-10.9-x86_64-3.8/stardist/plot
  copying stardist/plot/plot.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/plot
  copying stardist/plot/render.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/plot
  copying stardist/plot/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/plot
  creating build/lib.macosx-10.9-x86_64-3.8/stardist/models
  copying stardist/models/model3d.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/models
  copying stardist/models/model2d.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/models
  copying stardist/models/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/models
  copying stardist/models/base.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/models
  creating build/lib.macosx-10.9-x86_64-3.8/stardist/geometry
  copying stardist/geometry/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/geometry
  copying stardist/geometry/geom3d.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/geometry
  copying stardist/geometry/geom2d.py -> build/lib.macosx-10.9-x86_64-3.8/stardist/geometry
  creating build/lib.macosx-10.9-x86_64-3.8/stardist/kernels
  copying stardist/kernels/stardist2d.cl -> build/lib.macosx-10.9-x86_64-3.8/stardist/kernels
  copying stardist/kernels/stardist3d.cl -> build/lib.macosx-10.9-x86_64-3.8/stardist/kernels
  running build_ext
  building 'stardist.lib.stardist2d' extension
  Warning: Can't read registry to find the necessary compiler setting
  Make sure that Python modules winreg, win32api or win32con are installed.
  C compiler: gcc-9 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g
  
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/stardist
  creating build/temp.macosx-10.9-x86_64-3.8/stardist/lib
  compile options: '-I/private/var/folders/th/04d371mj4mgdzrv6rv0wn7v00000gn/T/pip-build-env-wvds_nia/overlay/lib/python3.8/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c'
  extra options: '-std=c++11 -fopenmp'
  gcc-9: stardist/lib/stardist2d.cpp
  gcc-9: stardist/lib/utils.cpp
  gcc-9: stardist/lib/clipper.cpp
  compiling with OpenMP support failed, re-trying without
  building 'stardist.lib.stardist2d' extension
  C compiler: gcc-9 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g
  
  compile options: '-I/private/var/folders/th/04d371mj4mgdzrv6rv0wn7v00000gn/T/pip-build-env-wvds_nia/overlay/lib/python3.8/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c'
  extra options: '-std=c++11'
  gcc-9: stardist/lib/stardist2d.cpp
  gcc-9: stardist/lib/clipper.cpp
  gcc-9: stardist/lib/utils.cpp
  error: Command "gcc-9 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/private/var/folders/th/04d371mj4mgdzrv6rv0wn7v00000gn/T/pip-build-env-wvds_nia/overlay/lib/python3.8/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c stardist/lib/stardist2d.cpp -o build/temp.macosx-10.9-x86_64-3.8/stardist/lib/stardist2d.o -std=c++11" failed with exit status 127
  ----------------------------------------
  ERROR: Failed building wheel for stardist
Failed to build stardist
ERROR: Could not build wheels for stardist which use PEP 517 and cannot be installed directly

**Comment by TMM-98** [comment]
Stupid me. I have gcc-10.

adjusted to `CC=/usr/local/bin/gcc-10 CXX=/usr/local/bin/g++-10 pip3 install stardist` everything works fine

**Comment by liuqs1990** [comment]
I already installed gcc 10.2.0 is already installed and up-to-date
but I still have the same problem....

**Comment by uschmidt83** [comment]
Hi @liuqs1990, we can't help you without knowing more details. What did you do and what happened?
