### ISSUE TITLE
Question : How can we use StarDist to annotate a images using Qupath

### ISSUE THREAD

**Issue by ramchandracheke** [mpicbg-csbd/stardist#81]
Hi,

Thank you for this great work! I have seen your video on youtube. (https://www.youtube.com/watch?v=Amn_eHRGX5M&t=4497s )
I am wondering how can I use startDist for accelerating annotation process using Qupath like (1:14:00 you have used a Automate-> Shared script-> StarDist2D). Currently, I can't see that option in my pc.

Thanks a million!

Best,
Ram

**Comment by uschmidt83** [comment]
Hi Ram,

we can't help you with that since we're no QuPath experts. You best option is to ask this question at the [image.sc forum](https://forum.image.sc/tag/qupath) using the tag `qupath`.

Best,
Uwe

**Comment by ramchandracheke** [comment]
Thanks a million Uwe!
I hope, I will find this answer in forum.

Thanks,
Ram
