### ISSUE TITLE
Why not have tensorflow in install_requires?

### ISSUE THREAD

**Issue by GFleishman** [mpicbg-csbd/stardist#83]
Not really an issue, but I'm wondering why you guys chose to instruct users to install tensorflow separately rather than have it as part of the install_requires list in setup.py? I'm trying to put stardist itself in the install_requires list for my own package, which will come with some pretrained stardist models for whole brain, nuclear localized, zebrafish confocal images, and while working out the details of packaging this seems important.

**Comment by maweigert** [comment]
Hi @GFleishman ,

As far as I remember, we opted against this as only very specific  tensorflow+cuda+cudnn combination are admissible on a specific machine depending on the nvidia driver (see [here](https://www.tensorflow.org/install/source#tested_build_configurations)) and we found that pip/conda typically do the respective dependency resolution only poorly (e.g. installs the wrong cudnn etc).

**Comment by uschmidt83** [comment]
For TensorFlow 1.x, there are two different packages ( `tensorflow` and `tensorflow-gpu`), which makes this complicated. For example, see discussion [here](https://github.com/tensorflow/tensorflow/issues/7166) or the existence of packages like [this](https://pypi.org/project/tensorflow-auto-detect/). Furthermore, Keras support(ed) other backends and we wanted to keep the option to use something else besides TensorFlow in the future.

None of these reasons are still valid if you only want to use the latest TensorFlow 2.x.
