### ISSUE TITLE
Test/mask dataset contains no segmentation boundaries in .tif images

### ISSUE THREAD

**Issue by smcope** [mpicbg-csbd/stardist#85]
When I download the sample dataset that you sourced from Kaggle 2018 Data Science Bowl I notice that the mask images do not have cell segmentation in mask images. Can you please explain why these images are all black? Same is also true in your example 2D .tif images. Thank you!

https://github.com/mpicbg-csbd/stardist/tree/master/tests/data
https://github.com/mpicbg-csbd/stardist/releases/download/0.1.0/dsb2018.zip

**Comment by uschmidt83** [comment]
I don't understand why you think that the images are all black. Did you open them with a software that knows how to display them properly (e.g. [Fiji](https://fiji.sc))?

For example, even my web browser can show this 2D example image properly:
https://raw.githubusercontent.com/mpicbg-csbd/stardist/master/tests/data/img2d.tif

Best,
Uwe
