### ISSUE TITLE
Instance prediction with overlap label produces IndexError

### ISSUE THREAD

**Issue by erjel** [mpicbg-csbd/stardist#86]
Hi Uwe and Martin,

I would like to predict instances with an overlap label in stardist 0.6.0 on several 3D volumes.

While some stacks work fine, some others produce an `IndexError`:

```
predicting instances with prob_thresh = 0.46082856676821055 and nms_thresh = 0.3
Non Maximum Suppression (3D) ++++
NMS: n_polys  = 560
NMS: n_rays   = 192
NMS: n_faces  = 380
NMS: thresh   = 0.300
NMS: use_bbox = 1
NMS: using OpenMP with 40 thread(s)
NMS: precompute volumes, bounding boxes, etc
precompute done
NMS: calculated anisotropy: 1.66         1.00    1.22
NMS: starting suppression loop
^M|#                                                 | [3 % suppressed]^M|###                                               | [8 % suppressed]^M|#####                                             | [12 % suppressed]^M|#######                                           | [1$
NMS: Function calls:
NMS: ~ bbox+out:    11008
NMS: ~ inner:         498
NMS: ~ kernel:        498
NMS: ~ convex:         47
NMS: ~ render:         47
NMS: Excluded intersection:
NMS: + pretest:     10510
NMS: + convex:          0
NMS: Function calls timing:
NMS: / kernel:   1.80 s  (3.61 ms per call)
NMS: / convex:   0.31 s  (6.54 ms per call)
NMS: / render:   1.36 s  (28.85 ms per call)
NMS: Suppressed polyhedra:
NMS: # inner:           0 / 560  (0.00 %)
NMS: # kernel:        451 / 560  (80.54 %)
NMS: # render:         46 / 560  (8.21 %)
NMS: # total:         497 / 560  (88.75 %)
NMS: # keeping         63 / 560  polyhedra (11.25 %)
+++++++++++++++ polyhedra to label +++++++++++++++
n_polys           = 63
n_rays            = 192
n_faces           = 380
nz, ny, nx        = 306 1024 1024
use_overlap_label = 1
overlap_label     = -1

found 560 candidates
non-maximum suppression...
NMS took 0.8227 s
keeping 63/560 polyhedra
render polygons...
Traceback (most recent call last):
  File "scripts/stardist_prediction.py", line 100, in <module>
    main(args.model_path, args.dataset_path, args.output_path, args.overlap)
  File "scripts/stardist_prediction.py", line 78, in main
    Y_ = [model.predict_instances(x, overlap_label=overlap_label, n_tiles=tuple(np.max([1, s//max_size]) for s in x.shape), verbose=True)[0] for x in tqdm(X)]
  File "scripts/stardist_prediction.py", line 78, in <listcomp>
    Y_ = [model.predict_instances(x, overlap_label=overlap_label, n_tiles=tuple(np.max([1, s//max_size]) for s in x.shape), verbose=True)[0] for x in tqdm(X)]
  File "/cobra/ptmp/ejelli/stardist_mpcdf_new/.snakemake/conda/9fa2cc17/lib/python3.7/site-packages/stardist/models/base.py", line 420, in predict_instances
    return self._instances_from_prediction(_shape_inst, prob, dist, prob_thresh=prob_thresh, nms_thresh=nms_thresh, overlap_label=overlap_label, **nms_kwargs)
  File "/cobra/ptmp/ejelli/stardist_mpcdf_new/.snakemake/conda/9fa2cc17/lib/python3.7/site-packages/stardist/models/model3d.py", line 498, in _instances_from_prediction
    labels[labels == fwd[overlap_label2]] = overlap_label
IndexError: index 64 is out of bounds for axis 0 with size 64
```

Do you have any idea how `fwd` can be of different length in just 2 [lines](https://github.com/mpicbg-csbd/stardist/blob/5359846a92ca466f07999f9efdb0fcc66ff4c3c5/stardist/models/model3d.py#L498) of code?

Best wishes,

Eric

**Comment by maweigert** [comment]
Hi @erjel,

Could you provide an example stack + the model folder such that I could reproduce the bug? (it works fine for me in general)

**Comment by erjel** [comment]
Hi Martin,

I wrote a [snakemake ](https://snakemake.readthedocs.io/en/stable/getting_started/installation.html) workflow including the prediction script, a sample file, and the conda environment definition, which might be useful for others as well. You can find it online:
https://datashare.mpcdf.mpg.de/s/RcTEahZ2NzoXciI

The trained model is stored password protected:
https://datashare.mpcdf.mpg.de/s/pq9Zns1CzWlnqms

I sent you the password to your staff email address at EPFL. 

If everthing is set up correctly,
` snakemake --use-conda -j`
should do the trick.

Note that the sample volume is very noisy and the training data is not directly matching the imaging conditions.

Tested with a Quadro RTX 5000 (16GB) and 92GB RAM.

Thanks for your time!

**Comment by maweigert** [comment]
Ok, that was indeed a bug in the overlap_label part (in particular, when there is no overlap pixel). That is fixed in the `dev` branch, which you can install with 

```pip install git+https://github.com/mpicbg-csbd/stardist@dev```

Thanks for reporting!

Sadly, judging from your images that seem to contain long rodlike bacteria (biofilm?) I don't think that StarDist will be very useful there. How much training data do you have?

**Comment by erjel** [comment]
Yes, I work with biofilms of rod shaped bacteria.

We have enough training data that we see a saturation in the prediction accuracy (i.e. figure 5 in your 3D paper). In general, the final accuracy values are equal or above the ones you measured in your WORM dataset (figure 4b).

**Comment by maweigert** [comment]
Ah, ok. Good to here that (the model and data you send me didn't seem to work for me, that's why I was pessimistic :)  

Let me know if the fixed `dev` branch works for you!

**Comment by erjel** [comment]
The `dev` branch works perfectly fine on my data. Thank you for the quick fix!

**Comment by maweigert** [comment]
Glad to hear! :)
