### ISSUE TITLE
stardist predictions not working anymore

### ISSUE THREAD

**Issue by pr4deepr** [mpicbg-csbd/stardist#88]
Hi
  I have been using StarDist3D for segmenting nuclei and recently been running into trouble. 
 I trained a custom model for segmenting nuclei in 3D stacks. predictions from the Python notebook and it was working a few weeks ago until past few days. When running a prediction in the Python notebook, it would get stuck/hang after the progress bar for the prediction is complete. I was using image stacks of 1024x1024x50; so I cropped out a 256x256x50 portion and would get an output stack with no labels.
To troubleshoot, I tried using a model I trained with data from the StarDist3D paper which was also working for me. I tried it on the test dataset (stacks 0027,28 and 29) and also got predictions with no labels. I got the following output in the notebook

```
predicting instances with prob_thresh = 0.5 and nms_thresh = 0.6
found 9 candidates
non-maximum suppression...
NMS took 0.0140 s
keeping 9/9 polyhedra
render polygons...
predicting instances with prob_thresh = 0.5 and nms_thresh = 0.6
found 2 candidates
non-maximum suppression...
NMS took 0.0100 s
keeping 2/2 polyhedra
render polygons...
predicting instances with prob_thresh = 0.5 and nms_thresh = 0.6
found 2 candidates
non-maximum suppression...
NMS took 0.0090 s
keeping 2/2 polyhedra
render polygons...
One example image is displayed bellow:
```
**&** 
command prompt for the three images:

```
2020-09-16 00:03:48.077111: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6685 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:2d:00.0, compute capability: 7.5)
2020-09-16 00:03:48.396788: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-09-16 00:03:49.106896: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: Invoking ptxas not supported on Windows
Relying on driver to perform ptx compilation. This message will be only logged once.
2020-09-16 00:03:49.495624: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
Non Maximum Suppression (3D) ++++
NMS: n_polys  = 9
NMS: n_rays   = 96
NMS: n_faces  = 188
NMS: thresh   = 0.600
NMS: use_bbox = 1
NMS: using OpenMP with 16 thread(s)
NMS: precompute volumes, bounding boxes, etc
precompute done
NMS: calculated anisotropy: 1.44         1.18    1.00
NMS: starting suppression loop

NMS: Function calls:
NMS: ~ bbox+out:       36
NMS: ~ inner:           0
NMS: ~ kernel:          0
NMS: ~ convex:          0
NMS: ~ render:          0
NMS: Excluded intersection:
NMS: + pretest:        36
NMS: + convex:          0
NMS: Function calls timing:
NMS: / kernel:   0.00 s  (0.00 ms per call)
NMS: / convex:   0.00 s  (0.00 ms per call)
NMS: / render:   0.00 s  (0.00 ms per call)
NMS: Suppressed polyhedra:
NMS: # inner:           0 / 9  (0.00 %)
NMS: # kernel:          0 / 9  (0.00 %)
NMS: # render:          0 / 9  (0.00 %)
NMS: # total:           0 / 9  (0.00 %)
NMS: # keeping          9 / 9  polyhedra (100.00 %)
+++++++++++++++ polyhedra to label +++++++++++++++
n_polys           = 9
n_rays            = 96
n_faces           = 188
nz, ny, nx        = 64 128 128
use_overlap_label = 0
overlap_label     = 0
Non Maximum Suppression (3D) ++++
NMS: n_polys  = 2
NMS: n_rays   = 96
NMS: n_faces  = 188
NMS: thresh   = 0.600
NMS: use_bbox = 1
NMS: using OpenMP with 16 thread(s)
NMS: precompute volumes, bounding boxes, etc
precompute done
NMS: calculated anisotropy: 2.00         1.00    1.00
NMS: starting suppression loop

NMS: Function calls:
NMS: ~ bbox+out:        1
NMS: ~ inner:           0
NMS: ~ kernel:          0
NMS: ~ convex:          0
NMS: ~ render:          0
NMS: Excluded intersection:
NMS: + pretest:         1
NMS: + convex:          0
NMS: Function calls timing:
NMS: / kernel:   0.00 s  (0.00 ms per call)
NMS: / convex:   0.00 s  (0.00 ms per call)
NMS: / render:   0.00 s  (0.00 ms per call)
NMS: Suppressed polyhedra:
NMS: # inner:           0 / 2  (0.00 %)
NMS: # kernel:          0 / 2  (0.00 %)
NMS: # render:          0 / 2  (0.00 %)
NMS: # total:           0 / 2  (0.00 %)
NMS: # keeping          2 / 2  polyhedra (100.00 %)
+++++++++++++++ polyhedra to label +++++++++++++++
n_polys           = 2
n_rays            = 96
n_faces           = 188
nz, ny, nx        = 64 128 128
use_overlap_label = 0
overlap_label     = 0
Non Maximum Suppression (3D) ++++
NMS: n_polys  = 2
NMS: n_rays   = 96
NMS: n_faces  = 188
NMS: thresh   = 0.600
NMS: use_bbox = 1
NMS: using OpenMP with 16 thread(s)
NMS: precompute volumes, bounding boxes, etc
precompute done
NMS: calculated anisotropy: -nan(ind)    -nan(ind)       -nan(ind)
NMS: starting suppression loop

NMS: Function calls:
NMS: ~ bbox+out:        1
NMS: ~ inner:           0
NMS: ~ kernel:          0
NMS: ~ convex:          0
NMS: ~ render:          0
NMS: Excluded intersection:
NMS: + pretest:         1
NMS: + convex:          0
NMS: Function calls timing:
NMS: / kernel:   0.00 s  (0.00 ms per call)
NMS: / convex:   0.00 s  (0.00 ms per call)
NMS: / render:   0.00 s  (0.00 ms per call)
NMS: Suppressed polyhedra:
NMS: # inner:           0 / 2  (0.00 %)
NMS: # kernel:          0 / 2  (0.00 %)
NMS: # render:          0 / 2  (0.00 %)
NMS: # total:           0 / 2  (0.00 %)
NMS: # keeping          2 / 2  polyhedra (100.00 %)
+++++++++++++++ polyhedra to label +++++++++++++++
n_polys           = 2
n_rays            = 96
n_faces           = 188
nz, ny, nx        = 64 128 128
use_overlap_label = 0
overlap_label     = 0
```

I had to wipe and reinstall my PC recently due to some issues. I configured the installation in Anaconda Navigator on Windows 10 PC, and tried both Tensorflow 2.2 (latest?) and Tensorflow 1.15 . 
I also tried this on the ZeroCost notebook and was getting the same error. 

I'm not sure what has changed and its been driving me nuts.
Please let me know if you need any other info.

Cheers
Pradeep

**Comment by maweigert** [comment]
Hi @pr4deepr,

It's hard to understand what the problem is. Please post a minimal example that demonstrates the issue that you are having. Does the [3D example](https://nbviewer.jupyter.org/github/mpicbg-csbd/stardist/blob/master/examples/3D/3_prediction.ipynb) work for you?

**Comment by pr4deepr** [comment]
Hi @maweigert 
  Thanks for responding. So, I tried the 3D example workbook. 
Yes, it does work for me which is great!

Now, I loaded a model I trained in StarDist3D using the test dataset from the paper and I get the error:
`ValueError: You are trying to load a weight file containing 18 layers into a model with 17 layers.`

Config file for the custom model:

`{"n_dim": 3, "axes": "ZYXC", "n_channel_in": 1, "n_channel_out": 97, "train_checkpoint": "weights_best.h5", "train_checkpoint_last": "weights_last.h5", "train_checkpoint_epoch": "weights_now.h5", "n_rays": 96, "grid": [1, 1, 1], "anisotropy": null, "backbone": "resnet", "rays_json": {"name": "Rays_GoldenSpiral", "kwargs": {"n": 96, "anisotropy": null}}, "resnet_n_blocks": 4, "resnet_kernel_size": [3, 3, 3], "resnet_kernel_init": "he_normal", "resnet_n_filter_base": 32, "resnet_n_conv_per_block": 3, "resnet_activation": "relu", "resnet_batch_norm": false, "net_conv_after_resnet": 128, "net_input_shape": [null, null, null, 1], "net_mask_shape": [null, null, null, 1], "train_patch_size": [128, 128, 128], "train_background_reg": 0.0001, "train_foreground_only": 0.9, "train_dist_loss": "mae", "train_loss_weights": [1, 0.2], "train_epochs": 400, "train_steps_per_epoch": 100, "train_learning_rate": 0.0003, "train_batch_size": 1, "train_n_val_patches": null, "train_tensorboard": true, "train_reduce_lr": {"factor": 0.5, "patience": 40, "min_delta": 0}, "use_gpu": false}`

Does this help?

Cheers
Pradeep

**Comment by maweigert** [comment]
Hi @pr4deepr ,

> Now, I loaded a model I trained in StarDist3D using the test dataset from the paper and I get the error:
> `ValueError: You are trying to load a weight file containing 18 layers into a model with 17 layers.`

What part of the code caused that error?

**Comment by pr4deepr** [comment]
Hi
  When I run this block:
```
demo_model = False

if demo_model:
    print (
        "NOTE: This is loading a previously trained demo model!\n"
        "      Please set the variable 'demo_model = False' to load your own trained model.",
        file=sys.stderr, flush=True
    )
    model = StarDist3D.from_pretrained('3D_demo')
else:
    model = StarDist3D(None, name='stardist_3d_dapi', basedir='models')
None;
```

The demo model works fine. This happens when I load a custom model trained in StarDist3D.

Thanks
Pradep

**Comment by maweigert** [comment]
Can you provide the `stardist_3d_dapi` model? Was it trained with our training notebook?

**Comment by pr4deepr** [comment]
Hi Martin
   The model file is [**here**](https://drive.google.com/file/d/18CppUNlIWdBZoKdSQMRMtT1ZN2ErzJlW/view?usp=sharing).
I did train this using the Zerocostdl4mic notebook. Would there be compatibility issues?

Cheers
Pradeep

**Comment by maweigert** [comment]
Hi @pr4deepr ,

Don't know what going on (I have no experience with Zerocostdl4mic). Maybe open an issue over there.

**Comment by pr4deepr** [comment]
Hi Martin
  When I run

model = StarDist3D(name='stardist_3d_dapi', basedir='models')

without the *None *parameter,

that error goes away. Not sure if this the right thing to do.

I can open a issue at Zerocostdl4mic as well..

Thanks
Pradeep

**Comment by maweigert** [comment]
Your weights file (`weights_best.h5`) and your config file differ, which might be an indicated that either of it was manipulated after training. Other than that, it's hard to see what is going on.

**Comment by pr4deepr** [comment]
Hi
  Thanks for that.
Would you mind letting me know where it differs.
I may retrain using your notebook and see if the errors persist.

Do you have any recommendations on what to keep track of so it will be
easier to troubleshoot if I have similar problems?

Cheers
Pradeep

**Comment by uschmidt83** [comment]
Hi @pr4deepr,

I've dug into this and found out that the `grid` parameter seems to have changed in the config somehow. I.e. when the model was trained and the weights were saved, the `grid` parameter had a value of 2 somewhere (e.g. `[1, 2, 2]`). But now, your config has a value of `[1, 1, 1]` for `grid`. Maybe these are the weights from a differently trained model, or you accidentally overwrote the config by creating a different model with the same name (i.e. in the same folder).

Best,
Uwe

**Comment by pr4deepr** [comment]
Hi @uschmidt83 

   Thanks for troubleshooting it for me. It is a possibility that I may have overwritten the folders. I have been playing around with StarDist a lot to get the right models. I'll be careful with the folders. 
Thanks again @maweigert as well for your help. 
I'm going to train the models again and see how I go with it. I like your updated notebooks especially the augment function. 

I will open this again if I am having similar issues!

Cheers
Pradeep
