### ISSUE TITLE
Filter nucleus on size

### ISSUE THREAD

**Issue by pymich** [mpicbg-csbd/stardist#91]
Great work, thanks!
I was wondering if there would be an easy way to filter nucleus based on their size in the python stardist 2D.
Predictions are mostly great but I'm struggling to eliminate a couple of small rounded artefacts in dirty smaples.
I thaught I might be able to filter on coord but they are all the same size.

Thanks!

**Comment by uschmidt83** [comment]
> I was wondering if there would be an easy way to filter nucleus based on their size in the python stardist 2D.

Yes, for example by using the [`regionsprops`](https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.regionprops) function from scikit-image:

```python
...

labels, details = model.predict_instances(img)

from skimage.measure import regionprops

threshold = 500

for region in regionprops(labels):
    if region.area < threshold:
        print(f"Removing label {region.label} with area {region.area}")
        labels[labels==region.label] = 0
```

Sorry for the late reply!

Best,
Uwe

**Comment by pymich** [comment]
Works fantastic. Thank you so much!
Best,
Michel
