### ISSUE TITLE
Training 3D model require same shape images?

### ISSUE THREAD

**Issue by asasama12** [mpicbg-csbd/stardist#92]
I'm working on creating a ground truth annotated image set for a 3D segmentation project and with my first batch of images, on the model.train line I get the error: all input images must have the same shape.  Does this mean that all of my annotated images must have the same shape in x, y, and z dimensions?  Some of my images have more or fewer z-planes than others.  Will this pose a problem when running the model on my images down the line?

**Comment by uschmidt83** [comment]
> Does this mean that all of my annotated images must have the same shape in x, y, and z dimensions?

No, but each training input image and its corresponding label image have to be the same shape in all dimensions. Also, the shape must be bigger or equal to the chosen `patch_size` for training.

> Some of my images have more or fewer z-planes than others. Will this pose a problem when running the model on my images down the line?

No, that isn't a technical requirement and should be fine.

Best,
Uwe
