### ISSUE TITLE
How to reload model?

### ISSUE THREAD

**Issue by Xqua** [mpicbg-csbd/stardist#95]
Hi, 

How does one reload a model after training in python ?
If it simply calling the model with the same name and basedir ? 

I have tried to .load_weights but it fails saying that it cannot load 18 layers onto a 17 layers model. 

Thanks !

**Comment by maweigert** [comment]
> How does one reload a model after training in python ?
> If it simply calling the model with the same name and basedir ?

Yes. If you set `config=None` in the constructor, the model (and weights) will be loaded from the name/basedir given:
```python
 model = StarDist2D(config=None, name=  ..., basedir =  ...)
```

**Comment by Xqua** [comment]
Perfect That works ! 
I've added it to the README and created a PR so that others might find it easily !

**Comment by maweigert** [comment]
Cool! Note that this is already stated in the docstring of the class model class (so imho might not be necessary to explicitly state it in the readme)

**Comment by Xqua** [comment]
IMHO, I didn't find it explicit in the DocString and went all the way to csbdeep to finally realize that this might be the case. At which point I tried to load it and had erased the previous model so it bugged XD 

Training a model is very time consuming and simply running a single command might destroy it so IMHO it is a valuable addition to the readme ^^ But I am on the repeat things over school ^^
